/**
 * Sync Engine — the core orchestrator for Morphkit continuous sync.
 *
 * Analyzes a web app, diffs the resulting semantic model against the
 * previously stored model in the iOS repo, regenerates only what changed,
 * and commits the result (optionally creating a GitHub PR).
 *
 * Designed to be used both from the CLI and programmatically.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync, mkdirSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve, join, relative, dirname } from 'node:path';

import { analyzeRepo } from '../analyzer/index.js';
import { generateProject } from '../generator/index.js';
import type { GeneratedFile } from '../generator/swiftui-generator.js';
import { adaptForPlatform } from '../semantic/adapter.js';
import { buildSemanticModel } from '../semantic/builder.js';
import type { SemanticAppModel } from '../semantic/model.js';

import { diffModels } from './model-diff.js';
import type { ModelDiff } from './model-diff.js';
import { generateBranchName, createSyncPR, generatePRBody } from './pr-generator.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface SyncOptions {
  /** Absolute or relative path to the web app source repo */
  sourceRepo: string;
  /** Absolute or relative path to the target iOS project repo */
  targetRepo: string;
  /** App name override (PascalCase) */
  appName?: string;
  /** Base branch for the PR (default: 'main') */
  baseBranch?: string;
  /** Whether to create a GitHub PR (default: true) */
  createPR?: boolean;
  /** Custom PR title */
  prTitle?: string;
  /** Print what would change without committing (default: false) */
  dryRun?: boolean;
}

export interface SyncResult {
  /** Files whose content was changed (added or modified) */
  changedFiles: string[];
  /** Files that are new (did not exist before) */
  addedFiles: string[];
  /** Files from previous generation that are no longer generated */
  removedFiles: string[];
  /** Files that had manual edits and were preserved */
  conflictFiles: string[];
  /** Git branch name created for the sync */
  branchName: string;
  /** GitHub PR URL (if created) */
  prUrl?: string;
  /** Manual instructions when PR could not be auto-created */
  manualInstructions?: string;
  /** The structural diff between old and new models */
  modelDiff: ModelDiff;
  /** Whether anything actually changed */
  hasChanges: boolean;
}

/** Metadata stored in .morphkit/sync.json */
export interface SyncMetadata {
  lastSyncTimestamp: string;
  sourceRepo: string;
  branchName: string;
  morphkitVersion: string;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const MORPHKIT_DIR = '.morphkit';
const MODEL_FILE = 'model.json';
const SYNC_FILE = 'sync.json';
const MORPHKIT_HEADER = '// Generated by Morphkit';
const MORPHKIT_VERSION = '0.2.0';

// ---------------------------------------------------------------------------
// Core sync
// ---------------------------------------------------------------------------

/**
 * Run a full sync cycle:
 *  1. Analyze the web app
 *  2. Diff against the previously stored model
 *  3. Regenerate the iOS project to a temp directory
 *  4. Compare generated files against existing target files
 *  5. Write only what changed
 *  6. Store the new model
 *  7. Commit + optionally create a PR
 */
export async function syncRepos(options: SyncOptions): Promise<SyncResult> {
  const sourcePath = resolve(options.sourceRepo);
  const targetPath = resolve(options.targetRepo);
  const baseBranch = options.baseBranch ?? 'main';
  const shouldCreatePR = options.createPR !== false;
  const dryRun = options.dryRun === true;

  // Validate paths
  if (!existsSync(sourcePath)) {
    throw new Error(`Source repo not found: ${sourcePath}`);
  }
  if (!existsSync(targetPath)) {
    throw new Error(`Target repo not found: ${targetPath}`);
  }

  // --- Step 1: Analyze the web app ---
  const analysisResult = await analyzeRepo(sourcePath);
  let model = await buildSemanticModel(analysisResult);

  if (options.appName) {
    model = { ...model, appName: options.appName };
  }

  const adapted = adaptForPlatform(model, 'ios');

  // --- Step 2: Load previous model and diff ---
  const morphkitDir = join(targetPath, MORPHKIT_DIR);
  const modelPath = join(morphkitDir, MODEL_FILE);

  let prevModel: SemanticAppModel | null = null;
  if (existsSync(modelPath)) {
    try {
      prevModel = JSON.parse(readFileSync(modelPath, 'utf-8')) as SemanticAppModel;
    } catch {
      // Corrupted model file — treat as fresh sync
      prevModel = null;
    }
  }

  const modelDiff = prevModel ? diffModels(prevModel, adapted) : buildFirstSyncDiff(adapted);

  // --- Step 3: Generate to a temp directory ---
  const tempDir = mkdtempSync(join(tmpdir(), 'morphkit-sync-'));
  let generatedProject;

  try {
    generatedProject = await generateProject(adapted, tempDir);
  } catch (err) {
    rmSync(tempDir, { recursive: true, force: true });
    throw err;
  }

  // --- Step 4: Smart file diffing ---
  const { changedFiles, addedFiles, removedFiles, conflictFiles } =
    diffFiles(generatedProject.files, targetPath, prevModel !== null);

  // Clean up temp dir
  rmSync(tempDir, { recursive: true, force: true });

  const branchName = generateBranchName();
  const hasChanges = changedFiles.length > 0;

  if (!hasChanges) {
    return {
      changedFiles: [],
      addedFiles: [],
      removedFiles: [],
      conflictFiles: [],
      branchName,
      modelDiff,
      hasChanges: false,
    };
  }

  if (dryRun) {
    return {
      changedFiles,
      addedFiles,
      removedFiles,
      conflictFiles,
      branchName,
      modelDiff,
      hasChanges: true,
    };
  }

  // --- Step 5: Write changed files to the target repo ---
  for (const file of generatedProject.files) {
    const relPath = file.path;
    if (changedFiles.includes(relPath)) {
      const fullPath = join(targetPath, relPath);
      mkdirSync(dirname(fullPath), { recursive: true });
      writeFileSync(fullPath, file.content, 'utf-8');
    }
  }

  // --- Step 6: Store the new model and sync metadata ---
  mkdirSync(morphkitDir, { recursive: true });
  writeFileSync(modelPath, JSON.stringify(adapted, null, 2), 'utf-8');

  const syncMeta: SyncMetadata = {
    lastSyncTimestamp: new Date().toISOString(),
    sourceRepo: sourcePath,
    branchName,
    morphkitVersion: MORPHKIT_VERSION,
  };
  writeFileSync(join(morphkitDir, SYNC_FILE), JSON.stringify(syncMeta, null, 2), 'utf-8');

  // Include .morphkit files in the commit
  const allChangedFiles = [
    ...changedFiles,
    join(MORPHKIT_DIR, MODEL_FILE),
    join(MORPHKIT_DIR, SYNC_FILE),
  ];

  // --- Step 7: Git commit + PR ---
  let prUrl: string | undefined;
  let manualInstructions: string | undefined;

  if (shouldCreatePR) {
    const commitMessage = `[Morphkit] Sync: ${modelDiff.summary}\n\nSource: ${sourcePath}\nChanged files: ${changedFiles.length}\nAdded: ${addedFiles.length}\nRemoved (flagged): ${removedFiles.length}`;

    const prResult = await createSyncPR({
      targetRepo: targetPath,
      baseBranch,
      branchName,
      changedFiles: allChangedFiles,
      addedFiles,
      removedFiles,
      conflictFiles,
      modelDiff,
      prTitle: options.prTitle,
      commitMessage,
    });

    prUrl = prResult.prUrl;
    manualInstructions = prResult.manualInstructions;
  }

  return {
    changedFiles,
    addedFiles,
    removedFiles,
    conflictFiles,
    branchName,
    prUrl,
    manualInstructions,
    modelDiff,
    hasChanges: true,
  };
}

// ---------------------------------------------------------------------------
// File diffing
// ---------------------------------------------------------------------------

interface FileDiffResult {
  /** Files that should be written (new or modified) */
  changedFiles: string[];
  /** Subset of changedFiles that are new */
  addedFiles: string[];
  /** Files from previous generation not in new generation */
  removedFiles: string[];
  /** Files that exist with manual edits — preserved, not overwritten */
  conflictFiles: string[];
}

/**
 * Compare generated files against the target repo on disk.
 *
 * - Identical content -> skip
 * - File doesn't exist -> add
 * - Content changed, has Morphkit header -> update
 * - Content changed, no Morphkit header -> conflict (preserve manual edit)
 */
function diffFiles(
  generatedFiles: GeneratedFile[],
  targetPath: string,
  hasPreviousModel: boolean,
): FileDiffResult {
  const changedFiles: string[] = [];
  const addedFiles: string[] = [];
  const conflictFiles: string[] = [];

  for (const file of generatedFiles) {
    const targetFile = join(targetPath, file.path);

    if (!existsSync(targetFile)) {
      // New file
      changedFiles.push(file.path);
      addedFiles.push(file.path);
      continue;
    }

    const existingContent = readFileSync(targetFile, 'utf-8');

    // Identical content — skip
    if (existingContent === file.content) {
      continue;
    }

    // Content differs — check if manually edited
    if (isManuallyEdited(existingContent)) {
      conflictFiles.push(file.path);
      continue;
    }

    // Content changed and file has Morphkit header — safe to update
    changedFiles.push(file.path);
  }

  // Detect removals: files that were in the previous model's generation
  // but are no longer generated. We only flag these, never auto-delete.
  const removedFiles: string[] = [];
  if (hasPreviousModel) {
    // We check for .swift files in known Morphkit directories that
    // aren't in the new generation set
    const generatedPaths = new Set(generatedFiles.map(f => f.path));
    const knownDirs = ['Views', 'Models', 'Networking', 'Navigation', 'State'];

    for (const dir of knownDirs) {
      const dirPath = join(targetPath, dir);
      if (!existsSync(dirPath)) continue;

      try {
        const entries = readdirRecursive(dirPath);
        for (const entry of entries) {
          const relPath = relative(targetPath, entry);
          if (relPath.endsWith('.swift') && !generatedPaths.has(relPath)) {
            // Only flag files with Morphkit header as removable
            const content = readFileSync(entry, 'utf-8');
            if (content.startsWith(MORPHKIT_HEADER)) {
              removedFiles.push(relPath);
            }
          }
        }
      } catch {
        // Directory read error — skip
      }
    }
  }

  return { changedFiles, addedFiles, removedFiles, conflictFiles };
}

/**
 * Check if a file was manually edited by looking for the Morphkit header.
 * A file without the header was either created manually or had the header removed.
 */
function isManuallyEdited(content: string): boolean {
  return !content.startsWith(MORPHKIT_HEADER);
}

/**
 * Recursively list all files in a directory.
 */
function readdirRecursive(dirPath: string): string[] {
  const results: string[] = [];

  try {
    const entries = readdirSync(dirPath, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = join(dirPath, entry.name);
      if (entry.isDirectory()) {
        results.push(...readdirRecursive(fullPath));
      } else {
        results.push(fullPath);
      }
    }
  } catch {
    // Ignore errors (e.g. permission denied)
  }

  return results;
}

// ---------------------------------------------------------------------------
// First sync helper
// ---------------------------------------------------------------------------

/**
 * Build a ModelDiff for the first sync (no previous model).
 * Everything is "added".
 */
function buildFirstSyncDiff(model: SemanticAppModel): ModelDiff {
  return {
    addedScreens: model.screens.map(s => s.name),
    removedScreens: [],
    modifiedScreens: [],
    addedEntities: model.entities.map(e => e.name),
    removedEntities: [],
    modifiedEntities: [],
    addedEndpoints: model.apiEndpoints.map(ep => `${ep.method}:${ep.url}`),
    removedEndpoints: [],
    modifiedEndpoints: [],
    changedNavigation: true,
    changedAuth: model.auth !== null,
    summary: `Initial sync: ${model.screens.length} screens, ${model.entities.length} entities, ${model.apiEndpoints.length} endpoints`,
  };
}
