import { describe, test, expect } from 'bun:test';
import { generateSwiftUIViews } from '../../src/generator/swiftui-generator';
import type { SemanticAppModel } from '../../src/semantic/model';

describe('SwiftUI View Generator', () => {
  const createModelWithScreens = (screens: any[]): SemanticAppModel => ({
    appName: 'TestApp',
    description: 'A test app',
    entities: [],
    screens,
    navigation: { type: 'stack', routes: [], tabs: [], deepLinks: [] },
    stateManagement: [],
    apiEndpoints: [],
    auth: null,
    theme: {
      colors: { primary: '#007AFF', secondary: '#5856D6', background: '#FFFFFF', surface: '#F2F2F7', text: '#000000', textSecondary: '#8E8E93' },
      typography: { heading: { fontFamily: 'system', fontSize: 28, fontWeight: 'bold' }, body: { fontFamily: 'system', fontSize: 17, fontWeight: 'regular' }, caption: { fontFamily: 'system', fontSize: 12, fontWeight: 'regular' } },
      spacing: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32 },
      borderRadius: {},
    },
  });

  test('generates a list view', () => {
    const model = createModelWithScreens([
      {
        name: 'ProductList',
        description: 'Shows a list of products',
        purpose: 'Browse and search products',
        sourceFile: 'app/products/page.tsx',
        sourceComponent: 'ProductList',
        layout: 'list',
        components: [],
        dataRequirements: [{ source: 'Product', fetchStrategy: 'api' as const, cardinality: 'many' as const, blocking: true, params: {} }],
        actions: [{ label: 'selectProduct', trigger: 'tap' as const, effect: { type: 'navigate' as const, target: 'productDetail', payload: {} }, destructive: false, requiresAuth: false }],
        stateBindings: [],
      },
    ]);

    const files = generateSwiftUIViews(model);
    expect(files.length).toBeGreaterThan(0);

    const listView = files.find(f => f.path.includes('ProductList'));
    expect(listView).toBeDefined();
    expect(listView!.content).toContain('struct ProductListView: View');
    expect(listView!.content).toContain('import SwiftUI');
    expect(listView!.content).toContain('var body: some View');
    expect(listView!.content).toContain('#Preview');
  });

  test('generates a form view', () => {
    const model = createModelWithScreens([
      {
        name: 'AddProduct',
        description: 'Form to add a new product',
        purpose: 'Create a new product entry',
        sourceFile: 'app/products/new/page.tsx',
        sourceComponent: 'AddProductForm',
        layout: 'form',
        components: [],
        dataRequirements: [],
        actions: [{ label: 'submit', trigger: 'submit' as const, effect: { type: 'mutate' as const, target: 'save', payload: {} }, destructive: false, requiresAuth: false }],
        stateBindings: [],
      },
    ]);

    const files = generateSwiftUIViews(model);
    const formView = files.find(f => f.path.includes('AddProduct'));
    expect(formView).toBeDefined();
    expect(formView!.content).toContain('Form');
  });

  test('generates a detail view', () => {
    const model = createModelWithScreens([
      {
        name: 'ProductDetail',
        description: 'Shows product details',
        purpose: 'View full product information',
        sourceFile: 'app/products/[id]/page.tsx',
        sourceComponent: 'ProductDetail',
        layout: 'detail',
        components: [],
        dataRequirements: [{ source: 'Product', fetchStrategy: 'api' as const, cardinality: 'one' as const, blocking: true, params: {} }],
        actions: [
          { label: 'addToCart', trigger: 'tap' as const, effect: { type: 'mutate' as const, target: 'addToCart', payload: {} }, destructive: false, requiresAuth: false },
          { label: 'share', trigger: 'tap' as const, effect: { type: 'share' as const, target: 'product', payload: {} }, destructive: false, requiresAuth: false },
        ],
        stateBindings: [],
      },
    ]);

    const files = generateSwiftUIViews(model);
    const detailView = files.find(f => f.path.includes('ProductDetail'));
    expect(detailView).toBeDefined();
    // Detail views use ScrollView or have product property
    expect(detailView!.content).toContain('struct ProductDetailView: View');
  });

  test('includes Morphkit header comment', () => {
    const model = createModelWithScreens([
      {
        name: 'Home',
        description: 'Home screen',
        purpose: 'Main landing page',
        sourceFile: 'app/page.tsx',
        sourceComponent: 'Home',
        layout: 'dashboard',
        components: [],
        dataRequirements: [],
        actions: [],
        stateBindings: [],
      },
    ]);

    const files = generateSwiftUIViews(model);
    for (const file of files) {
      expect(file.content).toContain('Generated by Morphkit');
    }
  });
});
