// Templates for generating navigation structure

export interface RouteDefinition {
  name: string;
  associatedValues?: { name: string; type: string }[];
}

export function generateRouterEnum(routes: RouteDefinition[]): string {
  const cases = routes.map(r => {
    if (r.associatedValues && r.associatedValues.length > 0) {
      const values = r.associatedValues.map(v => `${v.name}: ${v.type}`).join(', ');
      return `    case ${r.name}(${values})`;
    }
    return `    case ${r.name}`;
  }).join('\n');

  return `// Generated by Morphkit
import SwiftUI

enum AppRoute: Hashable {
${cases}
}
`;
}

export function generateRouter(routes: RouteDefinition[]): string {
  const destinationCases = routes.map(r => {
    const viewName = pascalCase(r.name) + 'View';
    if (r.associatedValues && r.associatedValues.length > 0) {
      const bindings = r.associatedValues.map(v => `let ${v.name}`).join(', ');
      const args = r.associatedValues.map(v => `${v.name}: ${v.name}`).join(', ');
      return `            case .${r.name}(${bindings}):
                ${viewName}(${args})`;
    }
    return `            case .${r.name}:
                ${viewName}()`;
  }).join('\n');

  return `// Generated by Morphkit
import SwiftUI

@Observable
final class Router {
    var path = NavigationPath()

    func navigate(to route: AppRoute) {
        path.append(route)
    }

    func goBack() {
        guard !path.isEmpty else { return }
        path.removeLast()
    }

    func popToRoot() {
        path = NavigationPath()
    }
}

struct RouterDestination: ViewModifier {
    func body(content: Content) -> some View {
        content
            .navigationDestination(for: AppRoute.self) { route in
                switch route {
${destinationCases}
                }
            }
    }
}

extension View {
    func withRouterDestinations() -> some View {
        modifier(RouterDestination())
    }
}
`;
}

export function generateNavigationStackRoot(rootView: string): string {
  return `NavigationStack(path: $router.path) {
    ${rootView}()
        .withRouterDestinations()
}`;
}

export function generateTabViewWithNavigation(
  tabs: { name: string; icon: string; view: string }[],
): string {
  const tabContent = tabs.map(t => `            Tab("${t.name}", systemImage: "${t.icon}") {
                NavigationStack {
                    ${t.view}()
                        .withRouterDestinations()
                }
            }`).join('\n');

  return `// Generated by Morphkit
import SwiftUI

struct ContentView: View {
    @State private var router = Router()

    var body: some View {
        TabView {
${tabContent}
        }
        .environment(router)
    }
}

#Preview {
    ContentView()
}
`;
}

function pascalCase(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
