// Templates for generating the networking layer

export interface EndpointConfig {
  name: string;
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  requestType?: string;
  responseType: string;
  requiresAuth: boolean;
  description: string;
}

export function generateAPIClient(
  baseURL: string,
  endpoints: EndpointConfig[],
  authStrategy: 'bearer' | 'cookie' | 'none',
): string {
  const endpointMethods = endpoints.map(generateEndpointMethod).join('\n\n');

  const authHeader = authStrategy === 'bearer'
    ? `
    var authToken: String? {
        get { UserDefaults.standard.string(forKey: "authToken") }
        set { UserDefaults.standard.set(newValue, forKey: "authToken") }
    }

    private func authenticatedRequest(_ request: inout URLRequest) {
        if let token = authToken {
            request.setValue("Bearer \\(token)", forHTTPHeaderField: "Authorization")
        }
    }`
    : '';

  return `// Generated by Morphkit
import Foundation

@Observable
final class APIClient {
    static let shared = APIClient()

    private let baseURL = URL(string: "${baseURL}")!
    private let decoder: JSONDecoder = {
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        decoder.dateDecodingStrategy = .iso8601
        return decoder
    }()
    private let encoder: JSONEncoder = {
        let encoder = JSONEncoder()
        encoder.keyEncodingStrategy = .convertToSnakeCase
        encoder.dateEncodingStrategy = .iso8601
        return encoder
    }()
${authHeader}

    private init() {}

${endpointMethods}

    // MARK: - Private Helpers

    private func request<T: Decodable>(
        method: String,
        path: String,
        body: (any Encodable)? = nil,
        requiresAuth: Bool = false
    ) async throws -> T {
        let url = baseURL.appendingPathComponent(path)
        var request = URLRequest(url: url)
        request.httpMethod = method
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")

        if requiresAuth {
            ${authStrategy === 'bearer' ? 'authenticatedRequest(&request)' : '// TODO: Add auth'}
        }

        if let body {
            request.httpBody = try encoder.encode(body)
        }

        let (data, response) = try await URLSession.shared.data(for: request)

        guard let httpResponse = response as? HTTPURLResponse else {
            throw NetworkError.invalidResponse
        }

        guard (200...299).contains(httpResponse.statusCode) else {
            throw NetworkError.httpError(statusCode: httpResponse.statusCode, data: data)
        }

        return try decoder.decode(T.self, from: data)
    }
}

enum NetworkError: LocalizedError {
    case invalidResponse
    case httpError(statusCode: Int, data: Data)
    case decodingError(Error)

    var errorDescription: String? {
        switch self {
        case .invalidResponse:
            return "Invalid response from server"
        case .httpError(let statusCode, _):
            return "HTTP error: \\(statusCode)"
        case .decodingError(let error):
            return "Failed to decode response: \\(error.localizedDescription)"
        }
    }
}
`;
}

function generateEndpointMethod(endpoint: EndpointConfig): string {
  const params: string[] = [];
  const pathWithInterpolation = endpoint.path.replace(/:(\w+)/g, (_, param) => {
    params.push(`${param}: String`);
    return `\\(${param})`;
  });

  if (endpoint.requestType && ['POST', 'PUT', 'PATCH'].includes(endpoint.method)) {
    params.push(`body: ${endpoint.requestType}`);
  }

  const paramString = params.length > 0 ? params.join(', ') : '';
  const bodyArg = endpoint.requestType && ['POST', 'PUT', 'PATCH'].includes(endpoint.method)
    ? ', body: body'
    : '';

  const returnType = endpoint.responseType === 'Void' ? '' : ` -> ${endpoint.responseType}`;
  const returnStatement = endpoint.responseType === 'Void'
    ? `let _: EmptyResponse = try await request(method: "${endpoint.method}", path: "${pathWithInterpolation}"${bodyArg}, requiresAuth: ${endpoint.requiresAuth})`
    : `return try await request(method: "${endpoint.method}", path: "${pathWithInterpolation}"${bodyArg}, requiresAuth: ${endpoint.requiresAuth})`;

  return `    /// ${endpoint.description}
    func ${endpoint.name}(${paramString}) async throws${returnType} {
        ${returnStatement}
    }`;
}

export function generateEmptyResponseType(): string {
  return `
struct EmptyResponse: Decodable {}
`;
}
