// Templates for generating SwiftUI views

export interface ViewConfig {
  name: string;
  sourceFile: string;
  stateProperties: StateProperty[];
  bodyContent: string;
  helperMethods: string[];
  imports: string[];
}

export interface StateProperty {
  wrapper: '@State' | '@Binding' | '@Environment' | '@Observable';
  name: string;
  type: string;
  defaultValue?: string;
}

export function generateView(config: ViewConfig): string {
  const imports = ['SwiftUI', ...config.imports]
    .map(i => `import ${i}`)
    .join('\n');

  const stateProps = config.stateProperties
    .map(p => {
      if (p.wrapper === '@Environment') {
        return `    @Environment(${p.type}.self) private var ${p.name}`;
      }
      const defaultVal = p.defaultValue ? ` = ${p.defaultValue}` : '';
      return `    ${p.wrapper} private var ${p.name}: ${p.type}${defaultVal}`;
    })
    .join('\n');

  const helpers = config.helperMethods.length > 0
    ? '\n' + config.helperMethods.map(m => indentBlock(m, 4)).join('\n\n')
    : '';

  return `// Generated by Morphkit from: ${config.sourceFile}
${imports}

struct ${config.name}: View {
${stateProps}

    var body: some View {
${indentBlock(config.bodyContent, 8)}
    }${helpers}
}

#Preview {
    ${config.name}()
}
`;
}

export function generateListView(
  name: string,
  sourceFile: string,
  itemType: string,
  rowContent: string,
  stateProperties: StateProperty[],
): string {
  return generateView({
    name,
    sourceFile,
    stateProperties: [
      ...stateProperties,
      { wrapper: '@State', name: 'items', type: `[${itemType}]`, defaultValue: '[]' },
      { wrapper: '@State', name: 'isLoading', type: 'Bool', defaultValue: 'false' },
    ],
    bodyContent: `NavigationStack {
    List(items) { item in
        NavigationLink(value: item) {
${indentBlock(rowContent, 12)}
        }
    }
    .navigationTitle("${name}")
    .overlay {
        if isLoading {
            ProgressView()
        }
    }
    .task {
        await loadItems()
    }
}`,
    helperMethods: [
      `private func loadItems() async {
    isLoading = true
    defer { isLoading = false }
    // TODO: Load items from API
}`,
    ],
    imports: [],
  });
}

export function generateFormView(
  name: string,
  sourceFile: string,
  fields: { name: string; type: string; label: string }[],
): string {
  const stateProperties: StateProperty[] = fields.map(f => ({
    wrapper: '@State' as const,
    name: f.name,
    type: f.type,
    defaultValue: getDefaultValue(f.type),
  }));

  const formFields = fields.map(f => {
    switch (f.type) {
      case 'String':
        return `TextField("${f.label}", text: $${f.name})`;
      case 'Bool':
        return `Toggle("${f.label}", isOn: $${f.name})`;
      case 'Date':
        return `DatePicker("${f.label}", selection: $${f.name})`;
      case 'Int':
      case 'Double':
        return `TextField("${f.label}", value: $${f.name}, format: .number)`;
      default:
        return `TextField("${f.label}", text: $${f.name})`;
    }
  }).join('\n');

  return generateView({
    name,
    sourceFile,
    stateProperties: [
      ...stateProperties,
      { wrapper: '@Environment', name: 'dismiss', type: '\\.dismiss' },
    ],
    bodyContent: `NavigationStack {
    Form {
        Section {
${indentBlock(formFields, 12)}
        }

        Section {
            Button("Save") {
                save()
            }
            .frame(maxWidth: .infinity)
        }
    }
    .navigationTitle("${name}")
    .toolbar {
        ToolbarItem(placement: .cancellationAction) {
            Button("Cancel") { dismiss() }
        }
    }
}`,
    helperMethods: [
      `private func save() {
    // TODO: Implement save
    dismiss()
}`,
    ],
    imports: [],
  });
}

export function generateDetailView(
  name: string,
  sourceFile: string,
  modelType: string,
  sections: { title: string; content: string }[],
): string {
  const sectionContent = sections
    .map(s => `Section("${s.title}") {\n${indentBlock(s.content, 4)}\n}`)
    .join('\n\n');

  return generateView({
    name,
    sourceFile,
    stateProperties: [],
    bodyContent: `ScrollView {
    VStack(alignment: .leading, spacing: 16) {
${indentBlock(sectionContent, 8)}
    }
    .padding()
}`,
    helperMethods: [],
    imports: [],
  });
}

export function generateTabView(
  tabs: { name: string; icon: string; view: string }[],
): string {
  const tabItems = tabs
    .map(t => `            Tab("${t.name}", systemImage: "${t.icon}") {
                ${t.view}()
            }`)
    .join('\n');

  return `// Generated by Morphkit
import SwiftUI

struct ContentView: View {
    var body: some View {
        TabView {
${tabItems}
        }
    }
}

#Preview {
    ContentView()
}
`;
}

function getDefaultValue(type: string): string {
  switch (type) {
    case 'String': return '""';
    case 'Bool': return 'false';
    case 'Int': return '0';
    case 'Double': return '0.0';
    case 'Date': return '.now';
    default: return '""';
  }
}

function indentBlock(content: string, spaces: number): string {
  const indent = ' '.repeat(spaces);
  return content
    .split('\n')
    .map(line => line.length > 0 ? `${indent}${line}` : line)
    .join('\n');
}
