// Template for generating the main App entry point

export function generateAppEntry(appName: string): string {
  return `// Generated by Morphkit
import SwiftUI

@main
struct ${appName}App: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
`;
}

export function generateAppEntryWithState(appName: string, storeNames: string[]): string {
  const storeDeclarations = storeNames
    .map(name => `    @State private var ${camelCase(name)} = ${name}()`)
    .join('\n');

  const environmentModifiers = storeNames
    .map(name => `                .environment(${camelCase(name)})`)
    .join('\n');

  return `// Generated by Morphkit
import SwiftUI

@main
struct ${appName}App: App {
${storeDeclarations}

    var body: some Scene {
        WindowGroup {
            ContentView()
${environmentModifiers}
        }
    }
}
`;
}

function camelCase(str: string): string {
  return str.charAt(0).toLowerCase() + str.slice(1);
}
