// Template for generating Swift data models

export interface SwiftProperty {
  name: string;
  type: string;
  optional: boolean;
  defaultValue?: string;
}

export interface SwiftModelConfig {
  name: string;
  properties: SwiftProperty[];
  protocols: string[];
  hasId: boolean;
  sourceFile: string;
}

export function generateSwiftModel(config: SwiftModelConfig): string {
  const protocols = config.protocols.length > 0
    ? `: ${config.protocols.join(', ')}`
    : '';

  const properties = config.properties
    .map(p => {
      const type = p.optional ? `${p.type}?` : p.type;
      const defaultVal = p.defaultValue ? ` = ${p.defaultValue}` : '';
      return `    var ${p.name}: ${type}${defaultVal}`;
    })
    .join('\n');

  // Generate CodingKeys if any property names need mapping
  const needsCodingKeys = config.properties.some(p => p.name.includes('_') || p.name !== camelCase(p.name));
  const codingKeys = needsCodingKeys
    ? generateCodingKeys(config.properties)
    : '';

  return `// Generated by Morphkit from: ${config.sourceFile}
import Foundation

struct ${config.name}${protocols} {
${properties}
}
${codingKeys}`;
}

export function generateSwiftEnum(name: string, cases: string[], sourceFile: string): string {
  const enumCases = cases.map(c => `    case ${camelCase(c)}`).join('\n');

  return `// Generated by Morphkit from: ${sourceFile}
import Foundation

enum ${name}: String, Codable, CaseIterable {
${enumCases}
}
`;
}

function generateCodingKeys(properties: SwiftProperty[]): string {
  const keys = properties
    .map(p => `        case ${camelCase(p.name)} = "${p.name}"`)
    .join('\n');

  return `
    enum CodingKeys: String, CodingKey {
${keys}
    }
`;
}

function camelCase(str: string): string {
  return str.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
}
