// Morphkit Navigation Generator
// Generates SwiftUI navigation structure from Semantic App Model

import type {
    SemanticAppModel,
    Screen,
    NavigationFlow,
    TabItem,
    ConfidenceLevel,
} from '../semantic/model';

import type { GeneratedFile } from './swiftui-generator';
import { pascalCase, camelCase, indent, isMarketingScreen } from './swiftui-generator';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Check if a screen needs an id parameter (detail layout with data requirements) */
function screenNeedsIdParam(screen: Screen): boolean {
    return screen.layout === 'detail' && screen.dataRequirements.length > 0;
}

/** Derive an entity-like name from a screen's first data requirement source */
function deriveEntity(screen: Screen): string | undefined {
    return screen.dataRequirements[0]?.source;
}

// ---------------------------------------------------------------------------
// Route enum generation
// ---------------------------------------------------------------------------

/** Check if a route has dynamic params (e.g. :id) */
function routeHasDynamicParams(model: SemanticAppModel, screen: Screen): boolean {
    const routes = model.navigation?.routes ?? [];
    const matchingRoute = routes.find((r) => r.screen === screen.name && r.params.length > 0);
    return !!matchingRoute;
}

/** Get a unique case name for a screen, appending "Detail" for dynamic-param routes */
function getRouteCaseName(model: SemanticAppModel, screen: Screen): string {
    const baseName = camelCase(screen.name);
    if (routeHasDynamicParams(model, screen) || screenNeedsIdParam(screen)) {
        // Avoid double "Detail" suffix — the builder's routePathToScreenName may have already appended it
        if (baseName.endsWith('Detail')) {
            return baseName;
        }
        return `${baseName}Detail`;
    }
    return baseName;
}

function generateRouteEnum(model: SemanticAppModel): string {
    const screens = (model.screens ?? []).filter((s) => !isMarketingScreen(s));
    const lines: string[] = [];
    const seenCases = new Set<string>();

    lines.push('// Generated by Morphkit');
    lines.push('');
    lines.push('import Foundation');
    lines.push('');
    lines.push('enum AppRoute: Hashable {');

    for (const screen of screens) {
        const caseName = getRouteCaseName(model, screen);
        if (seenCases.has(caseName)) continue;
        seenCases.add(caseName);

        const isDynamic = routeHasDynamicParams(model, screen) || screenNeedsIdParam(screen);
        if (isDynamic) {
            lines.push(`    case ${caseName}(id: String)`);
        } else {
            lines.push(`    case ${caseName}`);
        }
    }

    lines.push('}');

    return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Router / NavigationCoordinator
// ---------------------------------------------------------------------------

function generateRouter(model: SemanticAppModel): string {
    const screens = (model.screens ?? []).filter((s) => !isMarketingScreen(s));
    const nav = model.navigation;
    const lines: string[] = [];

    lines.push('// Generated by Morphkit');
    lines.push('');
    lines.push('import SwiftUI');
    lines.push('import Observation');
    lines.push('');
    lines.push('@Observable');
    lines.push('final class Router {');
    lines.push('    var path = NavigationPath()');
    const tabs = inferTabs(model);
    const defaultTab = tabs.length > 0 ? camelCase(tabs[0].label) : 'home';
    lines.push(`    var selectedTab: AppTab = .${defaultTab}`);
    lines.push('    var presentedSheet: AppRoute?');
    lines.push('');
    lines.push('    func navigate(to route: AppRoute) {');
    lines.push('        path.append(route)');
    lines.push('    }');
    lines.push('');
    lines.push('    func pop() {');
    lines.push('        guard !path.isEmpty else { return }');
    lines.push('        path.removeLast()');
    lines.push('    }');
    lines.push('');
    lines.push('    func popToRoot() {');
    lines.push('        path = NavigationPath()');
    lines.push('    }');
    lines.push('');
    lines.push('    func present(_ route: AppRoute) {');
    lines.push('        presentedSheet = route');
    lines.push('    }');
    lines.push('');
    lines.push('    func dismissSheet() {');
    lines.push('        presentedSheet = nil');
    lines.push('    }');
    lines.push('');
    lines.push('    // MARK: - Deep Linking');
    lines.push('');
    lines.push('    func handleDeepLink(_ url: URL) {');
    lines.push('        guard let components = URLComponents(url: url, resolvingAgainstBaseURL: false) else { return }');
    lines.push('        let pathComponents = components.path.split(separator: "/").map(String.init)');
    lines.push('');
    lines.push('        switch pathComponents.first {');

    const seenDeepLinkCases = new Set<string>();
    for (const screen of screens) {
        const caseName = getRouteCaseName(model, screen);
        if (seenDeepLinkCases.has(caseName)) continue;
        seenDeepLinkCases.add(caseName);

        const isDynamic = routeHasDynamicParams(model, screen) || screenNeedsIdParam(screen);
        // Use lowercased name for URL path matching (URL components are lowercase)
        const deepLinkPath = screen.name.toLowerCase();
        if (isDynamic) {
            lines.push(`        case "${deepLinkPath}":`);
            lines.push(`            if let id = pathComponents.dropFirst().first {`);
            lines.push(`                navigate(to: .${caseName}(id: id))`);
            lines.push('            }');
        } else {
            lines.push(`        case "${deepLinkPath}":`);
            lines.push(`            navigate(to: .${caseName})`);
        }
    }

    lines.push('        default:');
    lines.push('            break');
    lines.push('        }');
    lines.push('    }');
    lines.push('}');

    return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Tab enum
// ---------------------------------------------------------------------------

function generateTabEnum(model: SemanticAppModel): string {
    // Always use inferTabs to get all top-level routes as tabs
    // model.navigation.tabs may be incomplete (builder only sets entry point tabs)
    const tabs = inferTabs(model);
    const lines: string[] = [];

    lines.push('// Generated by Morphkit');
    lines.push('');
    lines.push('import SwiftUI');
    lines.push('');
    lines.push('enum AppTab: String, CaseIterable {');

    for (const tab of tabs) {
        lines.push(`    case ${camelCase(tab.label)}`);
    }

    lines.push('');
    lines.push('    var title: String {');
    lines.push('        switch self {');
    for (const tab of tabs) {
        lines.push(`        case .${camelCase(tab.label)}: return "${pascalCase(tab.label)}"`);
    }
    lines.push('        }');
    lines.push('    }');
    lines.push('');
    lines.push('    var systemImage: String {');
    lines.push('        switch self {');
    for (const tab of tabs) {
        lines.push(`        case .${camelCase(tab.label)}: return "${tab.icon ?? inferIcon(tab.label)}"`);
    }
    lines.push('        }');
    lines.push('    }');
    lines.push('}');

    return lines.join('\n');
}

function inferTabs(model: SemanticAppModel): TabItem[] {
    const routes = model.navigation?.routes ?? [];
    const screens = (model.screens ?? []).filter((s) => !isMarketingScreen(s));

    // Top-level routes: those with 0 or 1 path segments and no dynamic params
    const topLevelRoutes = routes.filter((r) => {
        const segments = r.path.split('/').filter(Boolean);
        return segments.length <= 1 && r.params.length === 0;
    });

    // Deduplicate by screen name and limit to 5
    const seenScreens = new Set<string>();
    const tabs: TabItem[] = [];
    for (const route of topLevelRoutes) {
        if (seenScreens.has(route.screen)) continue;
        seenScreens.add(route.screen);
        tabs.push({
            label: route.screen,
            icon: inferIcon(route.screen),
            screen: route.screen,
        });
        if (tabs.length >= 5) break;
    }

    if (tabs.length === 0) {
        // Fallback: use screens that look top-level (entry point or first few)
        const entryScreens = screens.filter((s) => s.isEntryPoint);
        if (entryScreens.length > 0) {
            return entryScreens.slice(0, 5).map((s) => ({
                label: s.name,
                icon: inferIcon(s.name),
                screen: s.name,
            }));
        }
        return [{ label: 'Home', icon: 'house', screen: screens[0]?.name ?? 'Home' }];
    }

    return tabs;
}

function inferIcon(name: string): string {
    const lower = name.toLowerCase();
    const iconMap: Record<string, string> = {
        home: 'house',
        dashboard: 'square.grid.2x2',
        settings: 'gearshape',
        profile: 'person',
        account: 'person.circle',
        search: 'magnifyingglass',
        favorites: 'heart',
        cart: 'cart',
        orders: 'list.clipboard',
        messages: 'message',
        chat: 'bubble.left.and.bubble.right',
        notifications: 'bell',
        discover: 'safari',
        explore: 'binoculars',
        activity: 'chart.bar',
        analytics: 'chart.line.uptrend.xyaxis',
        feed: 'newspaper',
        map: 'map',
        calendar: 'calendar',
        contacts: 'person.2',
        products: 'bag',
        categories: 'square.grid.3x3',
        more: 'ellipsis.circle',
    };

    for (const [key, icon] of Object.entries(iconMap)) {
        if (lower.includes(key)) return icon;
    }

    return 'circle';
}

// ---------------------------------------------------------------------------
// ContentView generation
// ---------------------------------------------------------------------------

function generateContentView(model: SemanticAppModel): string {
    const navType = model.navigation?.type ?? inferNavigationType(model);
    const appName = pascalCase(model.appName ?? 'App');

    switch (navType) {
        case 'tab':
            return generateTabContentView(model, appName);
        case 'stack':
            return generateStackContentView(model, appName);
        case 'mixed':
            return generateMixedContentView(model, appName);
        default:
            return generateStackContentView(model, appName);
    }
}

function inferNavigationType(model: SemanticAppModel): string {
    // Use inferred tabs count (based on top-level routes) rather than just isEntryPoint
    const tabs = inferTabs(model);
    if (tabs.length >= 2) return 'tab';
    return 'stack';
}

function generateTabContentView(model: SemanticAppModel, appName: string): string {
    // Always use inferred tabs — model.navigation.tabs is often incomplete
    const tabs = inferTabs(model);
    const hasAuth = model.auth != null;
    const lines: string[] = [];

    lines.push('// Generated by Morphkit');
    lines.push('');
    lines.push('import SwiftUI');
    lines.push('');
    lines.push('struct ContentView: View {');
    lines.push('    @State private var router = Router()');
    if (hasAuth) {
        lines.push('    @State private var showLogin = false');
    }
    lines.push('');
    lines.push('    var body: some View {');
    if (hasAuth) {
        lines.push('        Group {');
        lines.push('            if AuthManager.shared.isAuthenticated {');
        lines.push('                mainContent');
        lines.push('            } else {');
        lines.push('                LoginView()');
        lines.push('            }');
        lines.push('        }');
        lines.push('    }');
        lines.push('');
        lines.push('    private var mainContent: some View {');
    }
    lines.push('        TabView(selection: $router.selectedTab) {');

    for (const tab of tabs) {
        const viewName = `${pascalCase(tab.screen ?? tab.label)}View`;
        const tabCase = camelCase(tab.label);
        lines.push(`            ${viewName}()`);
        lines.push(`                .tabItem {`);
        lines.push(`                    Label(AppTab.${tabCase}.title, systemImage: AppTab.${tabCase}.systemImage)`);
        lines.push(`                }`);
        lines.push(`                .tag(AppTab.${tabCase})`);
    }

    lines.push('        }');
    lines.push('        .environment(router)');
    lines.push('        .onOpenURL { url in');
    lines.push('            router.handleDeepLink(url)');
    lines.push('        }');
    lines.push('    }');
    lines.push('}');
    lines.push('');
    lines.push('#Preview {');
    lines.push('    ContentView()');
    lines.push('}');

    return lines.join('\n');
}

function generateStackContentView(model: SemanticAppModel, appName: string): string {
    const screens = (model.screens ?? []).filter((s) => !isMarketingScreen(s));
    const rootScreen = screens.find((s) => s.isEntryPoint) ?? screens[0];
    const hasAuth = model.auth != null;
    const lines: string[] = [];

    lines.push('// Generated by Morphkit');
    lines.push('');
    lines.push('import SwiftUI');
    lines.push('');
    lines.push('struct ContentView: View {');
    lines.push('    @State private var router = Router()');
    lines.push('');
    lines.push('    var body: some View {');
    if (hasAuth) {
        lines.push('        Group {');
        lines.push('            if AuthManager.shared.isAuthenticated {');
        lines.push('                mainContent');
        lines.push('            } else {');
        lines.push('                LoginView()');
        lines.push('            }');
        lines.push('        }');
        lines.push('    }');
        lines.push('');
        lines.push('    private var mainContent: some View {');
    }
    lines.push('        NavigationStack(path: $router.path) {');

    if (rootScreen) {
        lines.push(`            ${pascalCase(rootScreen.name)}View()`);
    } else {
        lines.push('            Text("Welcome")');
    }

    lines.push('                .navigationDestination(for: AppRoute.self) { route in');
    lines.push('                    routeView(for: route)');
    lines.push('                }');
    lines.push('        }');
    lines.push('        .environment(router)');
    lines.push('        .onOpenURL { url in');
    lines.push('            router.handleDeepLink(url)');
    lines.push('        }');
    lines.push('    }');
    lines.push('');
    lines.push('    @ViewBuilder');
    lines.push('    private func routeView(for route: AppRoute) -> some View {');
    lines.push('        switch route {');

    const seenStackCases = new Set<string>();
    for (const screen of screens) {
        const caseName = getRouteCaseName(model, screen);
        if (seenStackCases.has(caseName)) continue;
        seenStackCases.add(caseName);

        const viewName = `${pascalCase(screen.name)}View`;
        const isDynamic = routeHasDynamicParams(model, screen) || screenNeedsIdParam(screen);
        if (isDynamic) {
            lines.push(`        case .${caseName}(let id):`);
            lines.push(`            ${viewName}(id: id)`);
        } else {
            lines.push(`        case .${caseName}:`);
            lines.push(`            ${viewName}()`);
        }
    }

    lines.push('        }');
    lines.push('    }');
    lines.push('}');
    lines.push('');
    lines.push('#Preview {');
    lines.push('    ContentView()');
    lines.push('}');

    return lines.join('\n');
}

function generateMixedContentView(model: SemanticAppModel, appName: string): string {
    // Always use inferred tabs — model.navigation.tabs is often incomplete
    const tabs = inferTabs(model);
    const screens = (model.screens ?? []).filter((s) => !isMarketingScreen(s));
    const lines: string[] = [];

    lines.push('// Generated by Morphkit');
    lines.push('');
    lines.push('import SwiftUI');
    lines.push('');
    lines.push('struct ContentView: View {');
    lines.push('    @State private var router = Router()');
    lines.push('');
    lines.push('    var body: some View {');
    lines.push('        TabView(selection: $router.selectedTab) {');

    for (const tab of tabs) {
        const viewName = `${pascalCase(tab.screen ?? tab.label)}View`;
        const tabCase = camelCase(tab.label);
        lines.push(`            NavigationStack {`);
        lines.push(`                ${viewName}()`);
        lines.push(`                    .navigationDestination(for: AppRoute.self) { route in`);
        lines.push(`                        routeView(for: route)`);
        lines.push(`                    }`);
        lines.push(`            }`);
        lines.push(`            .tabItem {`);
        lines.push(`                Label(AppTab.${tabCase}.title, systemImage: AppTab.${tabCase}.systemImage)`);
        lines.push(`            }`);
        lines.push(`            .tag(AppTab.${tabCase})`);
    }

    lines.push('        }');
    lines.push('        .environment(router)');
    lines.push('        .onOpenURL { url in');
    lines.push('            router.handleDeepLink(url)');
    lines.push('        }');
    lines.push('    }');
    lines.push('');
    lines.push('    @ViewBuilder');
    lines.push('    private func routeView(for route: AppRoute) -> some View {');
    lines.push('        switch route {');

    const seenMixedCases = new Set<string>();
    for (const screen of screens) {
        const caseName = getRouteCaseName(model, screen);
        if (seenMixedCases.has(caseName)) continue;
        seenMixedCases.add(caseName);

        const viewName = `${pascalCase(screen.name)}View`;
        const isDynamic = routeHasDynamicParams(model, screen) || screenNeedsIdParam(screen);
        if (isDynamic) {
            lines.push(`        case .${caseName}(let id):`);
            lines.push(`            ${viewName}(id: id)`);
        } else {
            lines.push(`        case .${caseName}:`);
            lines.push(`            ${viewName}()`);
        }
    }

    lines.push('        }');
    lines.push('    }');
    lines.push('}');
    lines.push('');
    lines.push('#Preview {');
    lines.push('    ContentView()');
    lines.push('}');

    return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function generateNavigation(model: SemanticAppModel): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const warnings: string[] = [];

    // Filter out marketing / static content screens from navigation
    const filteredScreens = (model.screens ?? []).filter((s) => !isMarketingScreen(s));
    const filteredScreenNames = new Set(filteredScreens.map(s => s.name));
    // Also filter routes that reference marketing screens
    const filteredRoutes = (model.navigation?.routes ?? []).filter(r => filteredScreenNames.has(r.screen));
    const filteredModel: SemanticAppModel = {
        ...model,
        screens: filteredScreens,
        navigation: { ...model.navigation, routes: filteredRoutes },
    };

    if (filteredScreens.length === 0) {
        warnings.push('No screens found in model — generating minimal navigation');
    }

    // AppRoute enum
    files.push({
        path: 'Navigation/AppRoute.swift',
        content: generateRouteEnum(filteredModel),
        sourceMapping: 'morphkit:navigation',
        confidence: filteredScreens.length > 0 ? 'high' : 'low',
        warnings: [],
    });

    // AppTab enum (always generate — even stack-only apps may evolve)
    files.push({
        path: 'Navigation/AppTab.swift',
        content: generateTabEnum(filteredModel),
        sourceMapping: 'morphkit:navigation',
        confidence: 'high',
        warnings: [],
    });

    // Router
    files.push({
        path: 'Navigation/Router.swift',
        content: generateRouter(filteredModel),
        sourceMapping: 'morphkit:navigation',
        confidence: 'high',
        warnings: [],
    });

    // ContentView
    const navType = filteredModel.navigation?.type ?? inferNavigationType(filteredModel);
    let contentConfidence: 'high' | 'medium' | 'low' = 'high';
    if (!filteredModel.navigation?.type) {
        contentConfidence = 'medium';
        warnings.push(`Navigation type inferred as "${navType}" — verify this matches the intended UX`);
    }

    files.push({
        path: 'ContentView.swift',
        content: generateContentView(filteredModel),
        sourceMapping: 'morphkit:navigation',
        confidence: contentConfidence,
        warnings,
    });

    return files;
}
