// Morphkit Xcode Project Generator
// Orchestrates all generators and writes a complete SwiftUI project to disk

import type {
    SemanticAppModel,
    ThemeConfig,
    ConfidenceLevel,
} from '../semantic/model';

import type { GeneratedFile } from './swiftui-generator';
import { generateSwiftUIViews, pascalCase, relativeSourcePath } from './swiftui-generator';
import { generateSwiftModels } from './model-generator';
import { generateNavigation } from './navigation-generator';
import { generateNetworkingLayer } from './networking-generator';

import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface GeneratedProject {
    appName: string;
    files: GeneratedFile[];
    outputPath: string;
    stats: {
        totalFiles: number;
        highConfidence: number;
        mediumConfidence: number;
        lowConfidence: number;
        warnings: string[];
    };
}

// ---------------------------------------------------------------------------
// App entry point generation
// ---------------------------------------------------------------------------

function generateAppEntry(model: SemanticAppModel): GeneratedFile {
    const appName = pascalCase(model.appName ?? 'MyApp');
    const lines: string[] = [];

    lines.push('// Generated by Morphkit');
    lines.push('');
    lines.push('import SwiftUI');
    lines.push('');
    lines.push('@main');
    lines.push(`struct ${appName}App: App {`);
    lines.push('    var body: some Scene {');
    lines.push('        WindowGroup {');
    lines.push('            ContentView()');
    lines.push('        }');
    lines.push('    }');
    lines.push('}');
    lines.push('');

    return {
        path: `${appName}App.swift`,
        content: lines.join('\n'),
        sourceMapping: 'morphkit:project',
        confidence: 'high',
        warnings: [],
    };
}

// ---------------------------------------------------------------------------
// Info.plist generation
// ---------------------------------------------------------------------------

function generateInfoPlist(model: SemanticAppModel): GeneratedFile {
    const appName = model.appName ?? 'MyApp';
    const bundleId = `com.example.${appName.toLowerCase().replace(/\s+/g, '')}`;

    const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>$(DEVELOPMENT_LANGUAGE)</string>
    <key>CFBundleDisplayName</key>
    <string>${appName}</string>
    <key>CFBundleExecutable</key>
    <string>$(EXECUTABLE_NAME)</string>
    <key>CFBundleIdentifier</key>
    <string>${bundleId}</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>$(PRODUCT_NAME)</string>
    <key>CFBundlePackageType</key>
    <string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>LSRequiresIPhoneOS</key>
    <true/>
    <key>UIApplicationSceneManifest</key>
    <dict>
        <key>UIApplicationSupportsMultipleScenes</key>
        <false/>
    </dict>
    <key>UILaunchScreen</key>
    <dict/>
    <key>UISupportedInterfaceOrientations</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
</dict>
</plist>`;

    return {
        path: 'Info.plist',
        content: plist,
        sourceMapping: 'morphkit:project',
        confidence: 'high',
        warnings: [],
    };
}

// ---------------------------------------------------------------------------
// Assets.xcassets generation
// ---------------------------------------------------------------------------

function generateAssets(model: SemanticAppModel): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const theme = model.theme;

    // Root Contents.json
    files.push({
        path: 'Assets.xcassets/Contents.json',
        content: JSON.stringify(
            {
                info: { author: 'xcode', version: 1 },
            },
            null,
            4,
        ),
        sourceMapping: 'morphkit:assets',
        confidence: 'high',
        warnings: [],
    });

    // AccentColor.colorset
    const accentColor = theme?.colors?.primary ?? '#007AFF';
    const rgb = hexToRGB(accentColor);

    files.push({
        path: 'Assets.xcassets/AccentColor.colorset/Contents.json',
        content: JSON.stringify(
            {
                colors: [
                    {
                        color: {
                            'color-space': 'srgb',
                            components: {
                                red: rgb.r.toFixed(3),
                                green: rgb.g.toFixed(3),
                                blue: rgb.b.toFixed(3),
                                alpha: '1.000',
                            },
                        },
                        idiom: 'universal',
                    },
                ],
                info: { author: 'xcode', version: 1 },
            },
            null,
            4,
        ),
        sourceMapping: 'morphkit:assets',
        confidence: theme?.colors?.primary ? 'high' : 'medium',
        warnings: theme?.colors?.primary ? [] : ['Using default accent color — update AccentColor.colorset'],
    });

    // AppIcon placeholder
    files.push({
        path: 'Assets.xcassets/AppIcon.appiconset/Contents.json',
        content: JSON.stringify(
            {
                images: [
                    {
                        idiom: 'universal',
                        platform: 'ios',
                        size: '1024x1024',
                    },
                ],
                info: { author: 'xcode', version: 1 },
            },
            null,
            4,
        ),
        sourceMapping: 'morphkit:assets',
        confidence: 'high',
        warnings: ['Add a 1024x1024 app icon image'],
    });

    return files;
}

function hexToRGB(hex: string): { r: number; g: number; b: number } {
    const clean = hex.replace('#', '');
    const num = parseInt(clean, 16);
    return {
        r: ((num >> 16) & 255) / 255,
        g: ((num >> 8) & 255) / 255,
        b: (num & 255) / 255,
    };
}

// ---------------------------------------------------------------------------
// State layer generation
// ---------------------------------------------------------------------------

/**
 * Clean a Zustand/Redux store name for Swift:
 *   - Strip leading 'Use'/'use' prefix (React hook convention)
 *   - Strip trailing 'Store'/'store' suffix (will be re-added)
 *   - Return PascalCase base name
 * e.g. 'useCartStore' → 'Cart', 'UseCartStore' → 'Cart', 'cartStore' → 'Cart'
 */
function cleanStoreName(raw: string): string {
    let name = raw;
    // Strip leading 'use' (case-insensitive)
    name = name.replace(/^[Uu]se/, '');
    // Strip trailing 'Store' (case-insensitive)
    name = name.replace(/[Ss]tore$/, '');
    // PascalCase the result
    if (name.length === 0) name = 'App';
    return pascalCase(name);
}

/**
 * Determine which entity names have associated API endpoints.
 * An entity is considered API-backed if any endpoint URL contains the
 * entity name (lowercase, singular or plural) or the response type
 * references it.
 */
function entitiesWithApiEndpoints(model: SemanticAppModel): Set<string> {
    const result = new Set<string>();
    const endpoints = model.apiEndpoints ?? [];

    for (const entity of model.entities ?? []) {
        const nameLower = entity.name.toLowerCase();
        for (const ep of endpoints) {
            const urlLower = ep.url.toLowerCase();
            // Check URL contains entity name (singular or plural)
            if (urlLower.includes(nameLower) || urlLower.includes(nameLower + 's')) {
                result.add(entity.name);
                break;
            }
            // Check response type references entity
            if (ep.responseType?.typeName?.toLowerCase() === nameLower) {
                result.add(entity.name);
                break;
            }
        }
    }

    return result;
}

/**
 * Detect sub-type entities that are used as fields of other entities
 * (e.g. CartItem is a sub-type of Cart because Cart has a CartItem[] field).
 * These should not get their own store.
 */
function getSubTypeEntityNames(model: SemanticAppModel): Set<string> {
    const subTypes = new Set<string>();
    const entities = model.entities ?? [];
    const entityNames = new Set(entities.map((e) => e.name));

    for (const entity of entities) {
        for (const field of entity.fields ?? []) {
            // Check if a field references another entity by name (direct or array)
            const referencedName =
                field.type.typeName ??
                field.type.elementType?.typeName;
            if (referencedName && entityNames.has(referencedName) && referencedName !== entity.name) {
                subTypes.add(referencedName);
            }
        }
    }

    return subTypes;
}

function generateStateLayer(model: SemanticAppModel): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const screens = model.screens ?? [];
    const statePatterns = model.stateManagement ?? [];

    // Determine which entities have API endpoints and which are sub-types
    const apiBackedEntities = entitiesWithApiEndpoints(model);
    const subTypeEntities = getSubTypeEntityNames(model);

    // --- Strategy 1: Zustand stores → consolidate into one store per web store ---
    // Each Zustand state pattern maps to a single Swift @Observable store.
    const zustandPatterns = statePatterns.filter((sp) => sp.source === 'zustand');
    const generatedStoreNames = new Set<string>();

    for (const sp of zustandPatterns) {
        const storeName = cleanStoreName(sp.name);
        // Skip if we already generated a store with this cleaned name
        if (generatedStoreNames.has(storeName)) continue;
        generatedStoreNames.add(storeName);

        const lines: string[] = [];
        lines.push(`// Generated by Morphkit from Zustand store: ${sp.name}`);
        lines.push('');
        lines.push('import SwiftUI');
        lines.push('import Observation');
        lines.push('');
        lines.push('@Observable');
        lines.push(`final class ${storeName}Store {`);

        // Add state properties from the Zustand shape
        if (sp.shape?.fields) {
            for (const field of sp.shape.fields) {
                const propName = field.name.charAt(0).toLowerCase() + field.name.slice(1);
                lines.push(`    var ${propName}: Any // TODO: replace with concrete type`);
            }
        } else {
            // Fallback: use store name to infer a collection property
            const varName = storeName.charAt(0).toLowerCase() + storeName.slice(1);
            lines.push(`    var ${varName}s: [${storeName}] = []`);
            lines.push(`    var selected${storeName}: ${storeName}?`);
        }

        lines.push('    var isLoading = false');
        lines.push('    var error: NetworkError?');
        lines.push('');
        lines.push('    private let apiClient: APIClient');
        lines.push('');
        lines.push('    init(apiClient: APIClient = .shared) {');
        lines.push('        self.apiClient = apiClient');
        lines.push('    }');

        // Add mutation methods from Zustand actions
        if (sp.mutations && sp.mutations.length > 0) {
            lines.push('');
            for (const mutation of sp.mutations) {
                const methodName = mutation.name.charAt(0).toLowerCase() + mutation.name.slice(1);
                lines.push(`    func ${methodName}() async {`);
                lines.push('        // TODO: implement');
                lines.push('    }');
            }
        } else {
            lines.push('');
            lines.push(`    func fetch${storeName}s() async {`);
            lines.push('        isLoading = true');
            lines.push('        error = nil');
            lines.push('');
            lines.push('        do {');
            const varName = storeName.charAt(0).toLowerCase() + storeName.slice(1);
            lines.push(`            ${varName}s = try await apiClient.fetch${storeName}s()`);
            lines.push('        } catch let networkError as NetworkError {');
            lines.push('            error = networkError');
            lines.push('        } catch {');
            lines.push('            self.error = .unknown(error)');
            lines.push('        }');
            lines.push('');
            lines.push('        isLoading = false');
            lines.push('    }');
        }

        lines.push('}');
        lines.push('');

        files.push({
            path: `State/${storeName}Store.swift`,
            content: lines.join('\n'),
            sourceMapping: sp.consumers?.[0] ?? 'unknown',
            confidence: 'medium',
            warnings: [
                `${storeName}Store generated from Zustand store "${sp.name}" — verify API methods`,
            ],
        });
    }

    // --- Strategy 2: Entity-based stores for non-Zustand apps ---
    // Only generate stores for entities that have API endpoints and are not sub-types.
    // Skip if Zustand stores already cover these entities.
    if (zustandPatterns.length === 0) {
        const entities = model.entities ?? [];

        for (const entity of entities) {
            // Skip enum entities (single __enum field)
            if (entity.fields.length === 1 && entity.fields[0]?.name === '__enum') continue;
            // Skip entities without API endpoints
            if (!apiBackedEntities.has(entity.name)) continue;
            // Skip sub-type entities (e.g. CartItem is part of Cart)
            if (subTypeEntities.has(entity.name)) continue;
            // Skip if a store with this name was already generated
            const name = pascalCase(entity.name);
            if (generatedStoreNames.has(name)) continue;
            generatedStoreNames.add(name);

            const varName = entity.name.charAt(0).toLowerCase() + entity.name.slice(1);
            const lines: string[] = [];

            lines.push(`// Generated by Morphkit from: ${relativeSourcePath(entity.sourceFile ?? 'unknown')}`);
            lines.push('');
            lines.push('import SwiftUI');
            lines.push('import Observation');
            lines.push('');
            lines.push('@Observable');
            lines.push(`final class ${name}Store {`);
            lines.push(`    var ${varName}s: [${name}] = []`);
            lines.push(`    var selected${name}: ${name}?`);
            lines.push('    var isLoading = false');
            lines.push('    var error: NetworkError?');
            lines.push('');
            lines.push('    private let apiClient: APIClient');
            lines.push('');
            lines.push('    init(apiClient: APIClient = .shared) {');
            lines.push('        self.apiClient = apiClient');
            lines.push('    }');
            lines.push('');
            lines.push(`    func fetch${name}s() async {`);
            lines.push('        isLoading = true');
            lines.push('        error = nil');
            lines.push('');
            lines.push('        do {');
            lines.push(`            ${varName}s = try await apiClient.fetch${name}s()`);
            lines.push('        } catch let networkError as NetworkError {');
            lines.push('            error = networkError');
            lines.push('        } catch {');
            lines.push('            self.error = .unknown(error)');
            lines.push('        }');
            lines.push('');
            lines.push('        isLoading = false');
            lines.push('    }');
            lines.push('}');
            lines.push('');

            files.push({
                path: `State/${name}Store.swift`,
                content: lines.join('\n'),
                sourceMapping: entity.sourceFile ?? 'unknown',
                confidence: 'medium',
                warnings: [
                    `${name}Store uses inferred API methods — verify method names match APIClient`,
                ],
            });
        }
    }

    // Generate per-screen ViewModels that group local state bindings
    for (const screen of screens) {
        if (screen.stateBindings.length === 0) continue;

        const viewModelName = `${pascalCase(screen.name)}ViewModel`;
        const lines: string[] = [];

        lines.push(`// Generated by Morphkit — ViewModel for ${screen.name} screen`);
        lines.push('');
        lines.push('import SwiftUI');
        lines.push('import Observation');
        lines.push('');
        lines.push('@Observable');
        lines.push(`final class ${viewModelName} {`);

        for (const binding of screen.stateBindings) {
            const propName = binding.charAt(0).toLowerCase() + binding.slice(1);
            // Infer a sensible type from the binding name
            if (binding.toLowerCase().startsWith('is') || binding.toLowerCase() === 'added') {
                lines.push(`    var ${propName} = false`);
            } else if (binding.toLowerCase().includes('query') || binding.toLowerCase().includes('search')) {
                lines.push(`    var ${propName} = ""`);
            } else if (binding.toLowerCase().includes('order') || binding.toLowerCase().includes('sort') || binding.toLowerCase().includes('category')) {
                lines.push(`    var ${propName} = ""`);
            } else {
                lines.push(`    var ${propName}: [Any] = []`);
            }
        }

        lines.push('    var isLoading = false');
        lines.push('    var error: NetworkError?');
        lines.push('}');
        lines.push('');

        files.push({
            path: `State/${viewModelName}.swift`,
            content: lines.join('\n'),
            sourceMapping: screen.sourceFile ?? 'unknown',
            confidence: 'medium',
            warnings: [
                `${viewModelName} state types are inferred — verify and replace with concrete types`,
            ],
        });
    }

    return files;
}

// ---------------------------------------------------------------------------
// Test stubs
// ---------------------------------------------------------------------------

function generateTestStubs(model: SemanticAppModel): GeneratedFile[] {
    const appName = pascalCase(model.appName ?? 'MyApp');
    const files: GeneratedFile[] = [];

    files.push({
        path: `../Tests/${appName}Tests.swift`,
        content: `// Generated by Morphkit

import Testing
@testable import ${appName}

@Suite("${appName} Tests")
struct ${appName}Tests {
    @Test func appLaunches() async throws {
        // Basic smoke test — app entry point compiles
        #expect(true)
    }
}
`,
        sourceMapping: 'morphkit:tests',
        confidence: 'high',
        warnings: [],
    });

    return files;
}

// ---------------------------------------------------------------------------
// README
// ---------------------------------------------------------------------------

function generateReadme(model: SemanticAppModel, stats: GeneratedProject['stats']): GeneratedFile {
    const appName = model.appName ?? 'MyApp';

    return {
        path: '../README.md',
        content: `# ${appName}

Generated by [Morphkit](https://github.com/ashlrai/morphkit) from web source analysis.

## Project Stats

- **Total files**: ${stats.totalFiles}
- **High confidence**: ${stats.highConfidence}
- **Medium confidence**: ${stats.mediumConfidence}
- **Low confidence**: ${stats.lowConfidence}

## Structure

\`\`\`
${appName}/
├── ${appName}App.swift       # App entry point
├── ContentView.swift          # Root navigation
├── Models/                    # Codable data models
├── Views/                     # SwiftUI views
├── Navigation/                # Router and routes
├── Networking/                # API client and DTOs
├── State/                     # Observable stores
└── Assets.xcassets/           # Colors and images
\`\`\`

## Requirements

- Xcode 15+
- iOS 17+
- Swift 5.9+

## Warnings

${stats.warnings.length > 0 ? stats.warnings.map((w) => `- ${w}`).join('\n') : 'None'}

## Notes

This project was automatically generated and may need manual adjustments:

1. Add your \`.xcodeproj\` / Swift Package — Morphkit does not generate the pbxproj file yet.
2. Replace placeholder API base URL in \`Networking/APIConfiguration.swift\`.
3. Add app icon to \`Assets.xcassets/AppIcon.appiconset/\`.
4. Review all files marked with "medium" or "low" confidence.
`,
        sourceMapping: 'morphkit:readme',
        confidence: 'high',
        warnings: [],
    };
}

// ---------------------------------------------------------------------------
// Xcode project note
// ---------------------------------------------------------------------------

function generateXcodeProjNote(model: SemanticAppModel): GeneratedFile {
    const appName = pascalCase(model.appName ?? 'MyApp');

    return {
        path: `../${appName}.xcodeproj/NOTE.md`,
        content: `# Xcode Project

Morphkit does not yet generate the \`.pbxproj\` file.

To create the Xcode project:

1. Open Xcode → File → New → Project → iOS App (SwiftUI)
2. Name it "${appName}"
3. Replace the generated files with the contents of the \`${appName}/\` folder
4. Build and run

Alternatively, use a Swift Package:
- Create a \`Package.swift\` and use the generated source files directly.
`,
        sourceMapping: 'morphkit:project',
        confidence: 'high',
        warnings: [],
    };
}

// ---------------------------------------------------------------------------
// Orchestrator
// ---------------------------------------------------------------------------

export async function generateXcodeProject(
    model: SemanticAppModel,
    outputPath: string,
): Promise<GeneratedProject> {
    const appName = pascalCase(model.appName ?? 'MyApp');
    const appDir = join(outputPath, appName);
    const allFiles: GeneratedFile[] = [];
    const allWarnings: string[] = [];

    // --- Run all generators ---

    // 1. Models
    const modelFiles = generateSwiftModels(model);
    allFiles.push(...modelFiles);

    // 2. Views
    const viewFiles = generateSwiftUIViews(model);
    allFiles.push(...viewFiles);

    // 3. Navigation
    const navFiles = generateNavigation(model);
    allFiles.push(...navFiles);

    // 4. Networking
    const networkFiles = generateNetworkingLayer(model);
    allFiles.push(...networkFiles);

    // 5. State
    const stateFiles = generateStateLayer(model);
    allFiles.push(...stateFiles);

    // 6. App entry
    allFiles.push(generateAppEntry(model));

    // 7. Info.plist
    allFiles.push(generateInfoPlist(model));

    // 8. Assets
    const assetFiles = generateAssets(model);
    allFiles.push(...assetFiles);

    // 9. Tests
    const testFiles = generateTestStubs(model);
    allFiles.push(...testFiles);

    // 10. Xcode project note
    allFiles.push(generateXcodeProjNote(model));

    // --- Calculate stats ---

    const stats: GeneratedProject['stats'] = {
        totalFiles: allFiles.length,
        highConfidence: allFiles.filter((f) => f.confidence === 'high').length,
        mediumConfidence: allFiles.filter((f) => f.confidence === 'medium').length,
        lowConfidence: allFiles.filter((f) => f.confidence === 'low').length,
        warnings: [],
    };

    // Collect all warnings
    for (const file of allFiles) {
        for (const w of file.warnings) {
            stats.warnings.push(`[${file.path}] ${w}`);
        }
    }

    // 11. README (needs stats)
    allFiles.push(generateReadme(model, stats));

    // Update total
    stats.totalFiles = allFiles.length;

    // --- Write files to disk ---

    for (const file of allFiles) {
        const fullPath = join(appDir, file.path);
        const dir = dirname(fullPath);

        await mkdir(dir, { recursive: true });
        await writeFile(fullPath, file.content, 'utf-8');
    }

    return {
        appName,
        files: allFiles,
        outputPath: appDir,
        stats,
    };
}
