// Morphkit Xcode Project Generator
// Orchestrates all generators and writes a complete SwiftUI project to disk

import { execSync, execFileSync } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname, normalize, resolve } from 'node:path';

import type {
    SemanticAppModel,
    ThemeConfig,
    ConfidenceLevel,
    TypeDefinition,
    Screen,
    Entity,
} from '../semantic/model';

import { generateSwiftModels, isJunkEntity, generateSwiftDataModels, generateDataManager, getSwiftDataEligibleEntities } from './model-generator';
import { generateNavigation } from './navigation-generator';
import { generateNetworkingLayer } from './networking-generator';
import { generateSwiftUIViews, generateErrorUIComponents, pascalCase, relativeSourcePath, isMarketingScreen, pluralize, cleanStoreName, getReferenceScreenNames } from './swiftui-generator';
import type { GeneratedFile } from './swiftui-generator';


// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface GeneratedProject {
    appName: string;
    files: GeneratedFile[];
    outputPath: string;
    stats: {
        totalFiles: number;
        highConfidence: number;
        mediumConfidence: number;
        lowConfidence: number;
        warnings: string[];
    };
}

// ---------------------------------------------------------------------------
// App entry point generation
// ---------------------------------------------------------------------------

function generateAppEntry(model: SemanticAppModel): GeneratedFile {
    const appName = pascalCase(model.appName ?? 'MyApp');
    const lines: string[] = [];

    const eligible = getSwiftDataEligibleEntities(model);
    const hasSwiftData = eligible.length > 0;

    lines.push('// Generated by Morphkit');
    lines.push('');
    lines.push('import SwiftUI');
    if (hasSwiftData) lines.push('import SwiftData');
    lines.push('');
    lines.push('@main');
    lines.push(`struct ${appName}App: App {`);
    lines.push('    var body: some Scene {');
    lines.push('        WindowGroup {');
    lines.push('            ContentView()');
    lines.push('        }');
    if (hasSwiftData) {
        const storeTypes = eligible.map(e => `${pascalCase(e.name)}Record.self`);
        lines.push(`        .modelContainer(for: [${storeTypes.join(', ')}])`);
    }
    lines.push('    }');
    lines.push('}');
    lines.push('');

    return {
        path: `${appName}App.swift`,
        content: lines.join('\n'),
        sourceMapping: 'morphkit:project',
        confidence: 'high',
        warnings: [],
    };
}

// ---------------------------------------------------------------------------
// Info.plist generation
// ---------------------------------------------------------------------------

function generateInfoPlist(model: SemanticAppModel): GeneratedFile {
    const appName = model.appName ?? 'MyApp';
    const bundleId = `com.example.${appName.toLowerCase().replace(/\s+/g, '')}`;

    const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>$(DEVELOPMENT_LANGUAGE)</string>
    <key>CFBundleDisplayName</key>
    <string>${appName}</string>
    <key>CFBundleExecutable</key>
    <string>$(EXECUTABLE_NAME)</string>
    <key>CFBundleIdentifier</key>
    <string>${bundleId}</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>$(PRODUCT_NAME)</string>
    <key>CFBundlePackageType</key>
    <string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>LSRequiresIPhoneOS</key>
    <true/>
    <key>UIApplicationSceneManifest</key>
    <dict>
        <key>UIApplicationSupportsMultipleScenes</key>
        <false/>
    </dict>
    <key>UILaunchScreen</key>
    <dict/>
    <key>UISupportedInterfaceOrientations</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
</dict>
</plist>`;

    return {
        path: 'Info.plist',
        content: plist,
        sourceMapping: 'morphkit:project',
        confidence: 'high',
        warnings: [],
    };
}

// ---------------------------------------------------------------------------
// Assets.xcassets generation
// ---------------------------------------------------------------------------

function generateAssets(model: SemanticAppModel): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const theme = model.theme;

    // Root Contents.json
    files.push({
        path: 'Assets.xcassets/Contents.json',
        content: JSON.stringify(
            {
                info: { author: 'xcode', version: 1 },
            },
            null,
            4,
        ),
        sourceMapping: 'morphkit:assets',
        confidence: 'high',
        warnings: [],
    });

    // AccentColor.colorset
    const accentColor = theme?.colors?.primary ?? '#007AFF';
    const rgb = hexToRGB(accentColor);

    files.push({
        path: 'Assets.xcassets/AccentColor.colorset/Contents.json',
        content: JSON.stringify(
            {
                colors: [
                    {
                        color: {
                            'color-space': 'srgb',
                            components: {
                                red: rgb.r.toFixed(3),
                                green: rgb.g.toFixed(3),
                                blue: rgb.b.toFixed(3),
                                alpha: '1.000',
                            },
                        },
                        idiom: 'universal',
                    },
                ],
                info: { author: 'xcode', version: 1 },
            },
            null,
            4,
        ),
        sourceMapping: 'morphkit:assets',
        confidence: theme?.colors?.primary ? 'high' : 'medium',
        warnings: theme?.colors?.primary ? [] : ['Using default accent color — update AccentColor.colorset'],
    });

    // AppIcon placeholder
    files.push({
        path: 'Assets.xcassets/AppIcon.appiconset/Contents.json',
        content: JSON.stringify(
            {
                images: [
                    {
                        idiom: 'universal',
                        platform: 'ios',
                        size: '1024x1024',
                    },
                ],
                info: { author: 'xcode', version: 1 },
            },
            null,
            4,
        ),
        sourceMapping: 'morphkit:assets',
        confidence: 'high',
        warnings: ['Add a 1024x1024 app icon image'],
    });

    return files;
}

function hexToRGB(hex: string): { r: number; g: number; b: number } {
    const clean = hex.replace(/^#/, '').slice(0, 6);
    if (!/^[0-9a-fA-F]{6}$/.test(clean)) {
        // Fallback to iOS default blue
        return { r: 0, g: 0.478, b: 1 };
    }
    const num = parseInt(clean, 16);
    return {
        r: ((num >> 16) & 255) / 255,
        g: ((num >> 8) & 255) / 255,
        b: (num & 255) / 255,
    };
}

// ---------------------------------------------------------------------------
// State layer generation
// ---------------------------------------------------------------------------

/**
 * Generate the default fetch method lines for a store.
 * Used by both Zustand-derived stores (when no mutations defined) and
 * entity-based stores to avoid duplicating the fetch boilerplate.
 */
function generateDefaultFetchMethod(storeName: string, model?: SemanticAppModel): string[] {
    const varName = storeName.charAt(0).toLowerCase() + storeName.slice(1);
    const lines: string[] = [];

    // Check if a plural fetch method (fetchProducts()) would exist in the generated APIClient
    // The APIClient generates fetchX() from endpoints where X matches the resource path segment
    const endpoints = model?.apiEndpoints ?? [];
    const pluralName = pluralize(storeName);
    // A plural fetch method exists when there's a GET endpoint whose path ends with the
    // plural resource name (e.g., /products, /api/products) AND has no path params
    // (parameterized endpoints like /posts/:id/comments generate fetchComment(postId:), not fetchComments())
    const hasFetchMethod = endpoints.some(ep => {
        if ((ep.method ?? 'GET') !== 'GET') return false;
        // Clean the URL: strip template literals, backticks, ${VAR} prefixes
        const url = (ep.url ?? '').replace(/`/g, '').replace(/\$\{[^}]+\}/g, '').toLowerCase();
        // Skip endpoints with path parameters
        if (url.includes(':') || url.includes('{') || url.includes('[')) return false;
        const lastSegment = url.split('/').filter(s => s && s !== 'api').pop() ?? '';
        return lastSegment === varName + 's' || lastSegment === varName;
    });

    lines.push('');
    lines.push(`    func fetch${pluralName}() async {`);
    lines.push('        isLoading = true');
    lines.push('        error = nil');
    lines.push('');

    if (hasFetchMethod) {
        lines.push('        do {');
        lines.push(`            ${varName}s = try await apiClient.fetch${pluralName}()`);
        lines.push('        } catch let networkError as NetworkError {');
        lines.push('            error = networkError');
        lines.push('        } catch {');
        lines.push('            self.error = .networkError(URLError(.unknown))');
        lines.push('        }');
    } else {
        // No matching API endpoint — generate a placeholder that compiles
        lines.push(`        // Fetch ${varName}s from your API`);
        lines.push(`        // apiClient.fetch${pluralName}() is not yet configured`);
        lines.push(`        // Add the endpoint to your API and uncomment:`);
        lines.push(`        // ${varName}s = try await apiClient.fetch${pluralName}()`);
    }

    lines.push('');
    lines.push('        isLoading = false');
    lines.push('    }');
    return lines;
}

/**
 * Generate the standard store boilerplate: collection property, selected item,
 * loading/error state, APIClient dependency, and initializer.
 */
function generateStoreBoilerplate(storeName: string): string[] {
    const varName = storeName.charAt(0).toLowerCase() + storeName.slice(1);
    const lines: string[] = [];
    lines.push(`    var ${varName}s: [${storeName}] = []`);
    lines.push(`    var selected${storeName}: ${storeName}?`);
    lines.push('    var isLoading = false');
    lines.push('    var error: NetworkError?');
    lines.push('');
    lines.push('    private let apiClient: APIClient');
    lines.push('');
    lines.push('    init(apiClient: APIClient = .shared) {');
    lines.push('        self.apiClient = apiClient');
    lines.push('    }');
    return lines;
}

/**
 * Determine which entity names have associated API endpoints.
 * An entity is considered API-backed if any endpoint URL contains the
 * entity name (lowercase, singular or plural) or the response type
 * references it.
 */
function entitiesWithApiEndpoints(model: SemanticAppModel): Set<string> {
    const result = new Set<string>();
    const endpoints = model.apiEndpoints ?? [];

    for (const entity of model.entities ?? []) {
        const nameLower = entity.name.toLowerCase();
        for (const ep of endpoints) {
            const urlLower = ep.url.toLowerCase();
            // Check URL contains entity name (singular or plural)
            if (urlLower.includes(nameLower) || urlLower.includes(nameLower + 's')) {
                result.add(entity.name);
                break;
            }
            // Check response type references entity
            if (ep.responseType?.typeName?.toLowerCase() === nameLower) {
                result.add(entity.name);
                break;
            }
        }
    }

    return result;
}

/**
 * Detect sub-type entities that are used as fields of other entities
 * (e.g. CartItem is a sub-type of Cart because Cart has a CartItem[] field).
 * These should not get their own store.
 */
function getSubTypeEntityNames(model: SemanticAppModel): Set<string> {
    const subTypes = new Set<string>();
    const entities = model.entities ?? [];
    const entityNames = new Set(entities.map((e) => e.name));

    for (const entity of entities) {
        for (const field of entity.fields ?? []) {
            // Check if a field references another entity by name (direct or array)
            const referencedName =
                field.type.typeName ??
                field.type.elementType?.typeName;
            if (referencedName && entityNames.has(referencedName) && referencedName !== entity.name) {
                subTypes.add(referencedName);
            }
        }
    }

    return subTypes;
}

/**
 * Resolve a Swift type for a Zustand store field by matching against model entities.
 * Falls back to heuristic type inference based on common field names.
 */
function resolveFieldType(
    fieldName: string,
    storeName: string,
    model: SemanticAppModel,
): string {
    const entities = model.entities ?? [];
    const entityNames = new Set(entities.map((e) => e.name));
    const lower = fieldName.toLowerCase();

    // "items" → look for a matching sub-entity (e.g. CartItem for Cart store)
    if (lower === 'items') {
        const itemEntity = `${storeName}Item`;
        if (entityNames.has(itemEntity)) return `[${itemEntity}] = []`;
        // Fallback: look for any entity with "Item" in name
        for (const e of entities) {
            if (e.name.endsWith('Item')) return `[${e.name}] = []`;
        }
        return '[Any] = [] // Replace with concrete item type';
    }

    // Numeric field names
    if (lower === 'total' || lower === 'subtotal' || lower === 'price' || lower === 'amount') {
        return 'Double = 0';
    }
    if (lower === 'quantity' || lower === 'count') {
        return 'Int = 0';
    }

    // Boolean field names
    if (lower.startsWith('is') || lower.startsWith('has') || lower === 'loading' || lower === 'added') {
        return 'Bool = false';
    }

    // String field names
    if (lower === 'error' || lower === 'message') {
        return 'String?';
    }

    // Try to match field name to an entity (e.g. "product" → Product?)
    const pascalField = fieldName.charAt(0).toUpperCase() + fieldName.slice(1);
    if (entityNames.has(pascalField)) {
        return `${pascalField}?`;
    }

    // Plural field → array of entity (e.g. "products" → [Product])
    if (lower.endsWith('s') && lower.length > 1) {
        const singular = pascalField.slice(0, -1);
        if (entityNames.has(singular)) return `[${singular}] = []`;
    }

    return 'Any // Replace with concrete type';
}

/**
 * Resolve an array element type from a screen name by finding a matching entity.
 * e.g. "Products" screen → "Product" entity, "Cart" screen → "CartItem" entity.
 */
function resolveArrayTypeFromScreenName(
    screenName: string,
    model: SemanticAppModel,
): string {
    const entities = model.entities ?? [];
    const entityNames = new Set(entities.map((e) => e.name));
    const pascal = pascalCase(screenName);

    // Try singular form: "Products" → "Product"
    if (pascal.endsWith('s') && pascal.length > 1) {
        const singular = pascal.slice(0, -1);
        if (entityNames.has(singular)) return singular;
    }

    // Try exact match
    if (entityNames.has(pascal)) return pascal;

    // Try with "Item" suffix: "Cart" → "CartItem"
    const itemName = `${pascal}Item`;
    if (entityNames.has(itemName)) return itemName;

    return 'Any';
}

function generateStateLayer(model: SemanticAppModel): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const screens = (model.screens ?? []).filter((s) => !isMarketingScreen(s));
    const statePatterns = model.stateManagement ?? [];

    // Determine which entities have API endpoints and which are sub-types
    const apiBackedEntities = entitiesWithApiEndpoints(model);
    const subTypeEntities = getSubTypeEntityNames(model);

    // --- Strategy 1: Zustand stores → consolidate into one store per web store ---
    // Each Zustand state pattern maps to a single Swift @Observable store.
    const zustandPatterns = statePatterns.filter((sp) => sp.source === 'zustand');
    const generatedStoreNames = new Set<string>();

    for (const sp of zustandPatterns) {
        const storeName = cleanStoreName(sp.name);
        // Skip if we already generated a store with this cleaned name
        if (generatedStoreNames.has(storeName)) continue;
        generatedStoreNames.add(storeName);

        const lines: string[] = [];
        lines.push(`// Generated by Morphkit from Zustand store: ${sp.name}`);
        lines.push('');
        lines.push('import SwiftUI');
        lines.push('import Observation');
        lines.push('');
        lines.push('@Observable');
        lines.push(`final class ${storeName}Store {`);

        // Add state properties from the Zustand shape (deduplicated)
        if (sp.shape?.fields) {
            const seenFieldNames = new Set<string>();
            for (const field of sp.shape.fields) {
                const propName = field.name.charAt(0).toLowerCase() + field.name.slice(1);
                if (seenFieldNames.has(propName)) continue;
                seenFieldNames.add(propName);

                // Try to resolve a concrete Swift type from model entities
                const resolvedType = resolveFieldType(propName, storeName, model);
                lines.push(`    var ${propName}: ${resolvedType}`);
            }
        } else {
            // Fallback: use store name to infer a collection property
            const varName = storeName.charAt(0).toLowerCase() + storeName.slice(1);
            lines.push(`    var ${varName}s: [${storeName}] = []`);
            lines.push(`    var selected${storeName}: ${storeName}?`);
        }

        // Only add isLoading/error if not already declared from shape fields
        const shapeFieldNames = sp.shape?.fields
            ? new Set(sp.shape.fields.map((f) => f.name.charAt(0).toLowerCase() + f.name.slice(1)))
            : new Set<string>();
        if (!shapeFieldNames.has('isLoading')) {
            lines.push('    var isLoading = false');
        }
        if (!shapeFieldNames.has('error')) {
            lines.push('    var error: NetworkError?');
        }
        lines.push('');
        lines.push('    private let apiClient: APIClient');
        lines.push('');
        lines.push('    init(apiClient: APIClient = .shared) {');
        lines.push('        self.apiClient = apiClient');
        lines.push('    }');

        // Add mutation methods from Zustand actions
        if (sp.mutations && sp.mutations.length > 0) {
            lines.push('');
            for (const mutation of sp.mutations) {
                const methodName = mutation.name.charAt(0).toLowerCase() + mutation.name.slice(1);
                lines.push(`    func ${methodName}() async {`);
                lines.push('        print("\\(#function) called")');
                lines.push('    }');
            }
        } else {
            lines.push(...generateDefaultFetchMethod(storeName, model));
        }

        lines.push('}');
        lines.push('');

        files.push({
            path: `State/${storeName}Store.swift`,
            content: lines.join('\n'),
            sourceMapping: sp.consumers?.[0] ?? 'unknown',
            confidence: 'medium',
            warnings: [
                `${storeName}Store generated from Zustand store "${sp.name}" — verify API methods`,
            ],
        });
    }

    // --- Strategy 2: Entity-based stores for non-Zustand apps ---
    // Only generate stores for entities that have API endpoints and are not sub-types.
    // Skip if Zustand stores already cover these entities.
    if (zustandPatterns.length === 0) {
        const entities = model.entities ?? [];

        for (const entity of entities) {
            // Skip enum entities (single __enum field)
            if (entity.fields.length === 1 && entity.fields[0]?.name === '__enum') continue;
            // Skip entities without API endpoints
            if (!apiBackedEntities.has(entity.name)) continue;
            // Skip sub-type entities (e.g. CartItem is part of Cart)
            if (subTypeEntities.has(entity.name)) continue;
            // Skip if a store with this name was already generated
            const name = pascalCase(entity.name);
            if (generatedStoreNames.has(name)) continue;
            generatedStoreNames.add(name);

            const lines: string[] = [];

            lines.push(`// Generated by Morphkit from: ${relativeSourcePath(entity.sourceFile ?? 'unknown')}`);
            lines.push('');
            lines.push('import SwiftUI');
            lines.push('import Observation');
            lines.push('');
            lines.push('@Observable');
            lines.push(`final class ${name}Store {`);
            lines.push(...generateStoreBoilerplate(name));
            lines.push(...generateDefaultFetchMethod(name, model));
            lines.push('}');
            lines.push('');

            files.push({
                path: `State/${name}Store.swift`,
                content: lines.join('\n'),
                sourceMapping: entity.sourceFile ?? 'unknown',
                confidence: 'medium',
                warnings: [
                    `${name}Store uses inferred API methods — verify method names match APIClient`,
                ],
            });
        }
    }

    // Generate per-screen ViewModels that group local state bindings
    for (const screen of screens) {
        if (screen.stateBindings.length === 0) continue;

        const viewModelName = `${pascalCase(screen.name)}ViewModel`;
        const lines: string[] = [];

        lines.push(`// Generated by Morphkit — ViewModel for ${screen.name} screen`);
        lines.push('');
        lines.push('import SwiftUI');
        lines.push('import Observation');
        lines.push('');
        lines.push('@Observable');
        lines.push(`final class ${viewModelName} {`);

        const declaredProps = new Set<string>();
        for (const binding of screen.stateBindings) {
            const propName = binding.charAt(0).toLowerCase() + binding.slice(1);
            // Skip duplicate property names
            if (declaredProps.has(propName)) continue;
            declaredProps.add(propName);

            // Infer type from the binding name
            const lower = binding.toLowerCase();
            if (lower.startsWith('is') || lower.startsWith('has') || lower.startsWith('show') || lower.startsWith('should') || lower === 'added' || lower.includes('loading') || lower.includes('loaded') || lower.includes('saving')) {
                lines.push(`    var ${propName} = false`);
            } else if (lower.includes('query') || lower.includes('search') || lower.includes('text') || lower.includes('input') || lower.includes('name') || lower.includes('email') || lower.includes('password')) {
                lines.push(`    var ${propName} = ""`);
            } else if (lower.includes('order') || lower.includes('sort') || lower.includes('category') || lower.includes('filter') || lower.includes('mode') || lower.includes('status') || lower.includes('type') || lower.includes('view')) {
                lines.push(`    var ${propName} = ""`);
            } else if (lower.includes('count') || lower.includes('index') || lower.includes('page') || lower.includes('total')) {
                lines.push(`    var ${propName} = 0`);
            } else if (lower.includes('error') || lower.includes('message')) {
                lines.push(`    var ${propName}: String?`);
            } else if (lower.includes('items') || lower.includes('list') || lower.includes('results') || lower.includes('ids') || lower.includes('collections')) {
                const entityType = resolveArrayTypeFromScreenName(screen.name, model);
                lines.push(`    var ${propName}: [${entityType}] = []`);
            } else if (lower.includes('id') || lower.includes('url') || lower.includes('token')) {
                lines.push(`    var ${propName}: String?`);
            } else if (lower.includes('date') || lower.includes('range')) {
                lines.push(`    var ${propName}: Date?`);
            } else {
                // Default to String for safety
                lines.push(`    var ${propName} = ""`);
            }
        }

        // Only add isLoading if not already declared from stateBindings
        if (!declaredProps.has('isLoading')) {
            lines.push('    var isLoading = false');
        }
        if (!declaredProps.has('error')) {
            lines.push('    var error: NetworkError?');
        }
        lines.push('}');
        lines.push('');

        files.push({
            path: `State/${viewModelName}.swift`,
            content: lines.join('\n'),
            sourceMapping: screen.sourceFile ?? 'unknown',
            confidence: 'medium',
            warnings: [
                `${viewModelName} state types are inferred — verify and replace with concrete types`,
            ],
        });
    }

    // --- AuthManager: generated when auth pattern is detected ---
    if (model.auth) {
        files.push({
            path: 'State/AuthManager.swift',
            content: generateAuthManager(model),
            sourceMapping: 'morphkit:auth',
            confidence: 'high',
            warnings: [],
        });
    }

    return files;
}

// ---------------------------------------------------------------------------
// Auth state manager generation
// ---------------------------------------------------------------------------

function generateAuthManager(model: SemanticAppModel): string {
    // Determine user type — look for a User entity
    const entities = model.entities ?? [];
    const userEntity = entities.find(e =>
        e.name.toLowerCase() === 'user' || e.name.toLowerCase() === 'currentuser' || e.name.toLowerCase() === 'profile',
    );
    const userTypeName = userEntity ? pascalCase(userEntity.name) : 'AuthUser';

    const lines: string[] = [];
    lines.push('// Generated by Morphkit');
    lines.push('');
    lines.push('import SwiftUI');
    lines.push('import Observation');
    lines.push('');
    lines.push('@Observable');
    lines.push('final class AuthManager {');
    lines.push('    static let shared = AuthManager()');
    lines.push('');
    lines.push('    var isAuthenticated: Bool { token != nil }');
    lines.push('    private(set) var token: String?');
    lines.push(`    private(set) var currentUser: ${userTypeName}?`);
    lines.push('');
    lines.push('    init() {');
    lines.push('        token = KeychainHelper.read(key: "authToken")');
    lines.push('        if let token {');
    lines.push('            APIClient.shared.setAuthToken(token)');
    lines.push('        }');
    lines.push('    }');
    lines.push('');
    lines.push('    // MARK: - Auth Actions');
    lines.push('');
    lines.push('    func login(email: String, password: String) async throws {');
    lines.push('        let response = try await APIClient.shared.login(email: email, password: password)');
    lines.push('        token = response.token');
    lines.push('        currentUser = response.user');
    lines.push('        try? KeychainHelper.save(key: "authToken", value: response.token)');
    lines.push('        APIClient.shared.setAuthToken(response.token)');
    lines.push('    }');
    lines.push('');
    lines.push('    func register(name: String, email: String, password: String) async throws {');
    lines.push('        let response = try await APIClient.shared.register(name: name, email: email, password: password)');
    lines.push('        token = response.token');
    lines.push('        currentUser = response.user');
    lines.push('        try? KeychainHelper.save(key: "authToken", value: response.token)');
    lines.push('        APIClient.shared.setAuthToken(response.token)');
    lines.push('    }');
    lines.push('');
    lines.push('    func logout() {');
    lines.push('        token = nil');
    lines.push('        currentUser = nil');
    lines.push('        KeychainHelper.delete(key: "authToken")');
    lines.push('        APIClient.shared.setAuthToken(nil)');
    lines.push('    }');
    lines.push('}');
    lines.push('');

    return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Test stubs
// ---------------------------------------------------------------------------

function generateTestStubs(model: SemanticAppModel): GeneratedFile[] {
    const appName = pascalCase(model.appName ?? 'MyApp');
    const files: GeneratedFile[] = [];

    files.push({
        path: `../Tests/${appName}Tests.swift`,
        content: `// Generated by Morphkit

import Testing
@testable import ${appName}

@Suite("${appName} Tests")
struct ${appName}Tests {
    @Test func appLaunches() async throws {
        // Basic smoke test — app entry point compiles
        #expect(true)
    }
}
`,
        sourceMapping: 'morphkit:tests',
        confidence: 'high',
        warnings: [],
    });

    return files;
}

// ---------------------------------------------------------------------------
// CLAUDE.md generation — AI-assistant-optimized project context
// ---------------------------------------------------------------------------

/**
 * Format a TypeDefinition as a human-readable shape string for CLAUDE.md.
 * e.g., `{ email: String, password: String }` or `[Product]`
 */
function formatTypeShape(td: TypeDefinition | null | undefined): string {
    if (!td) return 'unknown';
    switch (td.kind) {
        case 'string': return td.typeName ? pascalCase(td.typeName) : 'String';
        case 'number': return 'Number';
        case 'boolean': return 'Bool';
        case 'date': return 'Date';
        case 'array':
            return td.elementType ? `[${formatTypeShape(td.elementType)}]` : '[Any]';
        case 'object': {
            if (td.typeName) return pascalCase(td.typeName);
            if (td.fields && td.fields.length > 0) {
                const fieldStrs = td.fields.slice(0, 8).map(f =>
                    `${f.name}: ${formatTypeShape(f.type)}${f.optional ? '?' : ''}`
                );
                const suffix = td.fields.length > 8 ? ', ...' : '';
                return `{ ${fieldStrs.join(', ')}${suffix} }`;
            }
            return 'Object';
        }
        case 'enum':
            if (td.values && td.values.length > 0) {
                return td.values.slice(0, 6).map(v => `"${v}"`).join(' | ');
            }
            return td.typeName ? pascalCase(td.typeName) : 'String';
        case 'union':
            if (td.values && td.values.length > 0) {
                return td.values.slice(0, 6).map(v => `"${v}"`).join(' | ');
            }
            return td.typeName ? pascalCase(td.typeName) : 'Any';
        default:
            return 'Any';
    }
}

/** Clean an API URL for display — strip template literals, normalize params */
function cleanEndpointUrl(url: string): string {
    return url
        .replace(/`/g, '')
        .replace(/\$\{[^}]+\}/g, (match) => {
            const inner = match.slice(2, -1);
            // Keep path param references readable
            if (inner.includes('.') || inner.includes('[')) return ':param';
            return `:${inner}`;
        })
        .replace(/\/+/g, '/');
}

function generateClaudeMd(model: SemanticAppModel, stats: GeneratedProject['stats']): GeneratedFile {
    const appName = pascalCase(model.appName ?? 'MyApp');
    const screens = (model.screens ?? []).filter(s => !isMarketingScreen(s));
    const endpoints = model.apiEndpoints ?? [];
    const entities = model.entities ?? [];
    const auth = model.auth;
    const referenceScreenNames = getReferenceScreenNames(model);
    const lines: string[] = [];

    // ── Header ──
    lines.push(`# ${appName}`);
    lines.push('');
    lines.push(`> Generated by [Morphkit](https://morphkit.dev) — an AI-optimized iOS scaffold.`);
    lines.push(`> This project is designed to be completed by an AI coding assistant (Claude Code, Codex, etc.).`);
    lines.push('');

    if (model.description) {
        lines.push(`## What This App Does`);
        lines.push('');
        lines.push(model.description);
        lines.push('');
    }

    // ── Architecture ──
    lines.push('## Architecture (Do Not Change)');
    lines.push('');
    lines.push('- **UI Framework:** SwiftUI (iOS 17+)');
    lines.push('- **State:** `@Observable` classes (Swift 5.9 Observation framework, NOT ObservableObject)');
    lines.push('- **Navigation:** `NavigationStack` with typed `NavigationPath` router');
    lines.push('- **Networking:** `APIClient` singleton using `URLSession` + `async/await`');
    lines.push('- **Auth Storage:** iOS Keychain via `KeychainHelper` (NOT UserDefaults)');
    lines.push('- **Models:** `Codable` structs with `CodingKeys` for snake_case API responses');
    lines.push('- **Package Manager:** Swift Package Manager (`Package.swift` at project root)');
    lines.push('');

    // ── Build & Run ──
    lines.push('## Build & Run');
    lines.push('');
    lines.push('```bash');
    lines.push('# Open in Xcode');
    lines.push('open Package.swift');
    lines.push('');
    lines.push('# Or build from CLI');
    lines.push('swift build');
    lines.push('swift test');
    lines.push('```');
    lines.push('');

    // ── AI Assistant Integration ──
    lines.push('## AI Assistant Integration');
    lines.push('');
    lines.push('This project was generated with full Claude Code support:');
    lines.push('');
    lines.push('### Slash Commands');
    lines.push('- `/complete-screen <name>` — Complete a single screen by wiring API calls and implementing TODOs');
    lines.push('- `/verify` — Run verification and show completion status');
    lines.push('- `/next` — Get the next recommended screen to implement');
    lines.push('- `/complete-all` — Complete all remaining screens sequentially');
    lines.push('');
    lines.push('### MCP Tools');
    lines.push('- `morphkit_screen_context` — Get full context for a screen (view, models, API methods, reference patterns)');
    lines.push('- `morphkit_verify` — Check build status, TODO census, completion %');
    lines.push('- `morphkit_next_task` — Get the next recommended task');
    lines.push('');
    lines.push('The MCP server is auto-registered in `.claude/settings.json`. These tools are available immediately when you open this project in Claude Code.');
    lines.push('');

    // ── Quick Start Checklist ──
    // Compute incompleteEntities early so it's available here
    const incompleteEntities = entities.filter(e =>
        !isJunkEntity(e) && e.fields.length <= 1 && !(e.fields.length === 1 && e.fields[0]?.name === '__enum')
    );

    lines.push('## Quick Start Checklist');
    lines.push('');
    lines.push('After opening the project, complete these steps to get a working app:');
    lines.push('');
    lines.push('- [ ] Set your API base URL in `Networking/APIConfiguration.swift`');
    if (auth) {
        lines.push('- [ ] Implement authentication — wire login/signup to your backend');
    }
    if (referenceScreenNames.size > 0) {
        lines.push(`- [ ] Study the reference implementations (${[...referenceScreenNames].slice(0, 3).map(n => `\`${pascalCase(n)}View\``).join(', ')}) — these show the canonical pattern`);
    }
    lines.push('- [ ] Wire remaining screens by following the reference pattern');
    if (incompleteEntities.length > 0) {
        lines.push(`- [ ] Complete ${incompleteEntities.length} incomplete data model(s) — add real fields from your API schema`);
    }
    lines.push('');

    // ── Project Structure ──
    lines.push('## Project Structure');
    lines.push('');
    lines.push('```');
    lines.push(`${appName}/`);
    lines.push(`├── ${appName}App.swift       # App entry point`);
    lines.push('├── ContentView.swift          # Root TabView + NavigationStack');
    lines.push('├── Models/                    # Codable data models');
    lines.push('├── Views/                     # SwiftUI views (one per screen)');
    lines.push('├── Navigation/                # Router, AppRoute, AppTab');
    lines.push('├── Networking/                # APIClient, APIConfiguration, KeychainHelper');
    lines.push('├── State/                     # @Observable store classes');
    lines.push('└── Assets.xcassets/           # Colors and images');
    lines.push('```');
    lines.push('');

    // ── API Contract ──
    if (endpoints.length > 0) {
        lines.push('## API Contract');
        lines.push('');
        lines.push('These are the endpoints extracted from the web app source code. The `APIClient` has stub methods for these — implement the actual HTTP calls.');
        lines.push('');

        // Group by base path
        const grouped = new Map<string, typeof endpoints>();
        for (const ep of endpoints) {
            const url = cleanEndpointUrl(ep.url);
            const segments = url.split('/').filter(s => s && s !== 'api');
            const group = segments[0] ?? 'other';
            if (!grouped.has(group)) grouped.set(group, []);
            grouped.get(group)!.push(ep);
        }

        for (const [group, eps] of grouped) {
            lines.push(`### ${pascalCase(group)}`);
            lines.push('');
            lines.push('| Method | Endpoint | Auth | Request Body | Response | Description |');
            lines.push('|--------|----------|------|-------------|----------|-------------|');
            for (const ep of eps) {
                const url = cleanEndpointUrl(ep.url);
                const method = ep.method ?? 'GET';
                const authStr = ep.auth ? 'Yes' : 'No';
                const reqBody = ep.requestBody ? `\`${formatTypeShape(ep.requestBody)}\`` : '—';
                const resType = `\`${formatTypeShape(ep.responseType)}\``;
                const desc = ep.description || '—';
                lines.push(`| \`${method}\` | \`${url}\` | ${authStr} | ${reqBody} | ${resType} | ${desc} |`);
            }
            lines.push('');
        }
    }

    // ── Authentication ──
    if (auth) {
        lines.push('## Authentication');
        lines.push('');
        lines.push(`- **Type:** ${auth.type.toUpperCase()}`);
        if (auth.provider) {
            lines.push(`- **Provider:** ${auth.provider}`);
        }
        lines.push(`- **iOS Storage:** Keychain (via \`KeychainHelper.save(key: "authToken", value: token)\`)`);
        lines.push('');
        if (auth.flows && auth.flows.length > 0) {
            lines.push('**Auth Flows:**');
            lines.push('');
            for (const flow of auth.flows) {
                lines.push(`- **${flow.name}**: ${flow.description || flow.screens.join(' → ')}`);
                if (flow.endpoints.length > 0) {
                    lines.push(`  - Endpoints: ${flow.endpoints.map(e => `\`${e}\``).join(', ')}`);
                }
            }
            lines.push('');
        }
    }

    // ── Entity/Model Reference ──
    if (entities.length > 0) {
        lines.push('## Data Models');
        lines.push('');
        lines.push('These are the data entities extracted from the web app. Some may have incomplete fields — check the web app source for the complete shape.');
        lines.push('');

        if (incompleteEntities.length > 0) {
            lines.push(`> **${incompleteEntities.length} model(s) marked INCOMPLETE** — these only have a placeholder \`id\` field because the TypeScript source type was not exported, had fewer than 2 properties, or was only referenced by name without a definition. To fix: add the real fields from your API response schema or TypeScript interfaces.`);
            lines.push('');
        }

        const meaningfulEntities = entities.filter(e =>
            !isJunkEntity(e) && !(e.fields.length === 1 && e.fields[0]?.name === '__enum')
        );

        for (const entity of meaningfulEntities) {
            const fieldCount = entity.fields.length;
            const status = fieldCount <= 1 ? ' ⚠️ INCOMPLETE' : '';
            lines.push(`### ${pascalCase(entity.name)}${status}`);
            if (entity.description) {
                lines.push(`${entity.description}`);
            }
            lines.push('');
            if (entity.fields.length > 0) {
                lines.push('| Field | Type | Optional | Notes |');
                lines.push('|-------|------|----------|-------|');
                for (const field of entity.fields) {
                    const typeStr = formatTypeShape(field.type);
                    const opt = field.optional ? 'Yes' : 'No';
                    const notes = field.isPrimaryKey ? 'Primary Key' : (field.description || '—');
                    lines.push(`| \`${field.name}\` | \`${typeStr}\` | ${opt} | ${notes} |`);
                }
                lines.push('');
            }
            if (entity.sourceFile) {
                lines.push(`*Source: \`${relativeSourcePath(entity.sourceFile)}\`*`);
                lines.push('');
            }
        }
    }

    // ── Screen Inventory ──
    lines.push('## Screen Inventory');
    lines.push('');
    lines.push('| Screen | Layout | File | Status | Notes |');
    lines.push('|--------|--------|------|--------|-------|');

    for (const screen of screens) {
        const isRef = referenceScreenNames.has(screen.name);
        const status = isRef ? 'REFERENCE IMPL' : 'Scaffold + TODOs';
        const layout = screen.layout ?? 'custom';
        const file = `Views/${pascalCase(screen.name)}View.swift`;
        const purpose = screen.purpose || screen.description || '—';
        lines.push(`| ${screen.name} | ${layout} | \`${file}\` | ${status} | ${purpose} |`);
    }
    lines.push('');

    if (referenceScreenNames.size > 0) {
        lines.push('### Reference Implementations');
        lines.push('');
        lines.push('These screens are fully wired with API calls, error handling, and loading states. **Study these as the canonical pattern** for implementing all other screens:');
        lines.push('');
        for (const name of referenceScreenNames) {
            lines.push(`- \`Views/${pascalCase(name)}View.swift\` — complete data loading, error handling, and user actions`);
        }
        lines.push('');
        lines.push('All other screens follow the same architecture but have `// TODO:` comments where you need to wire up API calls and business logic.');
        lines.push('');
    }

    // ── Prioritized TODO List ──
    lines.push('## Implementation Priority');
    lines.push('');
    lines.push('Complete these in order for the fastest path to a working app:');
    lines.push('');

    const todoItems: string[] = [];

    // 1. API base URL
    todoItems.push('1. **Set API base URL** in `Networking/APIConfiguration.swift` — replace the placeholder URL with your actual API endpoint');

    // 2. Auth
    if (auth) {
        const authScreen = screens.find(s => s.layout === 'auth');
        const authFile = authScreen ? `Views/${pascalCase(authScreen.name)}View.swift` : 'the auth view';
        todoItems.push(`2. **Wire authentication** in ${authFile} — implement login/signup using \`KeychainHelper\` for token storage`);
    }

    // 3. Core screens (non-reference)
    let todoNum = auth ? 3 : 2;
    const coreScreens = screens.filter(s => !referenceScreenNames.has(s.name) && s.layout !== 'auth');
    if (coreScreens.length > 0) {
        todoItems.push(`${todoNum}. **Implement remaining screens** — follow the reference implementations above to wire up:`);
        for (const s of coreScreens.slice(0, 8)) {
            const apiReqs = (s.dataRequirements ?? []).filter(r => r.fetchStrategy === 'api');
            const detail = apiReqs.length > 0
                ? ` (needs: ${apiReqs.map(r => `\`${r.source}\``).join(', ')})`
                : '';
            todoItems.push(`   - \`${pascalCase(s.name)}View\`${detail}`);
        }
        if (coreScreens.length > 8) {
            todoItems.push(`   - ...and ${coreScreens.length - 8} more screens`);
        }
        todoNum++;
    }

    // 4. Incomplete models
    if (incompleteEntities.length > 0) {
        todoItems.push(`${todoNum}. **Complete data models** — these models need fields added: ${incompleteEntities.slice(0, 5).map(e => `\`${pascalCase(e.name)}\``).join(', ')}${incompleteEntities.length > 5 ? ` and ${incompleteEntities.length - 5} more` : ''}`);
        todoNum++;
    }

    // 5. Polish
    todoItems.push(`${todoNum}. **Polish UI** — add loading states, empty states, error handling, and pull-to-refresh to all screens`);

    for (const item of todoItems) {
        lines.push(item);
    }
    lines.push('');

    // ── Patterns & Conventions ──
    lines.push('## Patterns & Conventions');
    lines.push('');
    lines.push('### Data Loading Pattern');
    lines.push('```swift');
    lines.push('// Every view that loads data follows this pattern:');
    lines.push('struct ExampleView: View {');
    lines.push('    @State private var items: [Item] = []');
    lines.push('    @State private var isLoading = false');
    lines.push('    @State private var errorMessage: String?');
    lines.push('');
    lines.push('    var body: some View {');
    lines.push('        List { /* ... */ }');
    lines.push('            .task { await loadData() }');
    lines.push('            .refreshable { await loadData() }');
    lines.push('    }');
    lines.push('');
    lines.push('    private func loadData() async {');
    lines.push('        isLoading = true');
    lines.push('        defer { isLoading = false }');
    lines.push('        do {');
    lines.push('            items = try await APIClient.shared.fetchItems()');
    lines.push('        } catch {');
    lines.push('            errorMessage = error.localizedDescription');
    lines.push('        }');
    lines.push('    }');
    lines.push('}');
    lines.push('```');
    lines.push('');
    lines.push('### Auth Token Pattern');
    lines.push('```swift');
    lines.push('// Store token after login:');
    lines.push('KeychainHelper.save(key: "authToken", value: token)');
    lines.push('');
    lines.push('// APIClient automatically reads token for authenticated requests:');
    lines.push('// Set via: APIClient.shared.setAuthToken(token)');
    lines.push('```');
    lines.push('');
    lines.push('### Navigation Pattern');
    lines.push('```swift');
    lines.push('// Navigate programmatically:');
    lines.push('router.navigate(to: .productDetail(id: product.id.uuidString))');
    lines.push('');
    lines.push('// NavigationLink with route:');
    lines.push('.navigationDestination(for: AppRoute.self) { route in');
    lines.push('    // Router handles this in ContentView');
    lines.push('}');
    lines.push('```');
    lines.push('');

    // ── Troubleshooting ──
    lines.push('## Troubleshooting');
    lines.push('');
    lines.push('| Error | Cause | Fix |');
    lines.push('|-------|-------|-----|');
    lines.push('| `Cannot convert value of type \'[X]\' to type \'Y\'` | API fetch returns array but state var is scalar (or vice versa) | Change the `@State` declaration to match the API return type |');
    lines.push('| `Cannot find type \'X\' in scope` | Entity model was filtered or incomplete | Add the missing struct to `Models/` with `Codable` conformance |');
    lines.push('| `No such module \'X\'` | Missing Swift Package dependency | Add the package in `Package.swift` under `dependencies` |');
    lines.push('| `Type \'X\' does not conform to \'Decodable\'` | Model has a field with a non-Codable type | Ensure all field types conform to `Codable`, or mark the field as `@CodableIgnored` |');
    lines.push('| `// TODO:` in loadData() | Morphkit detected a type mismatch and emitted a safe placeholder | Read the TODO comment for the specific mismatch and fix the types |');
    lines.push('');

    // ── Swift Conventions (Step 7) ──
    lines.push('## Swift Conventions (Must Follow)');
    lines.push('');
    lines.push('These rules prevent common AI coding mistakes in this project:');
    lines.push('');
    lines.push('| Rule | Wrong | Right |');
    lines.push('|------|-------|-------|');
    lines.push('| Observable pattern | `class Store: ObservableObject` | `@Observable class Store` |');
    lines.push('| Task lifecycle | `.onAppear { Task { await load() } }` | `.task { await load() }` |');
    lines.push('| Token storage | `UserDefaults.standard.set(token, ...)` | `KeychainHelper.save(key: "authToken", value: token)` |');
    lines.push('| ForEach identity | `ForEach(items) { item in` | `ForEach(items, id: \\.id) { item in` or conform to `Identifiable` |');
    lines.push('| State access | `@State var name = ""` | `@State private var name = ""` |');
    lines.push('| Async button | `Button("Save") { await save() }` | `Button("Save") { Task { await save() } }` |');
    lines.push('| Navigation | `NavigationView { }` | `NavigationStack { }` |');
    lines.push('| Preview macro | `struct X_Previews: PreviewProvider` | `#Preview { }` |');
    lines.push('| Error handling | `try! await ...` | `do { try await ... } catch { errorMessage = error.localizedDescription }` |');
    lines.push('| List deletion | `.onDelete` with non-binding array | `.swipeActions { Button(role: .destructive) { } }` |');
    lines.push('');

    // ── Completion Manifest (Step 4) ──
    lines.push('## Completion Manifest');
    lines.push('');
    lines.push('Machine-readable project state for AI tooling. Do not edit manually.');
    lines.push('');
    lines.push('```json');

    const manifestScreens = screens.map(s => {
        const isRef = referenceScreenNames.has(s.name);
        const apiReqs = (s.dataRequirements ?? []).filter(r => r.fetchStrategy === 'api');
        const apiMethods = apiReqs.map(r => {
            const source = r.source ?? '';
            return `fetch${pascalCase(source.endsWith('s') ? source : pluralize(source))}`;
        });
        // Determine navigation targets from actions
        const navTargets = (s.actions ?? [])
            .filter(a => a.effect?.type === 'navigate')
            .map(a => pascalCase(a.effect?.target ?? ''))
            .filter(Boolean);

        const entry: Record<string, unknown> = {
            name: s.name,
            file: `Views/${pascalCase(s.name)}View.swift`,
            status: isRef ? 'reference' : 'scaffold',
            layout: s.layout ?? 'custom',
        };
        if (!isRef) {
            entry.todoCount = '?'; // Will be filled by verify
        }
        if (apiMethods.length > 0) entry.apiMethods = apiMethods;
        if (navTargets.length > 0) entry.navigatesTo = navTargets;
        return entry;
    });

    const manifest = {
        screens: manifestScreens,
        incompleteModels: incompleteEntities.map(e => pascalCase(e.name)),
        unwiredEndpoints: endpoints
            .filter(ep => {
                const url = ep.url.toLowerCase();
                return !url.includes('auth') && !url.includes('login') && !url.includes('register');
            })
            .map(ep => `${ep.method ?? 'GET'} ${ep.url.replace(/`/g, '').replace(/\$\{[^}]+\}/g, ':param')}`),
        completionOrder: screens
            .filter(s => !referenceScreenNames.has(s.name))
            .map(s => s.name),
    };

    lines.push(JSON.stringify(manifest, null, 2));
    lines.push('```');
    lines.push('');

    // ── Warnings ──
    if (stats.warnings.length > 0) {
        lines.push('## Build Warnings');
        lines.push('');
        const uniqueWarnings = [...new Set(stats.warnings)].slice(0, 20);
        for (const w of uniqueWarnings) {
            lines.push(`- ${w}`);
        }
        lines.push('');
    }

    return {
        path: '../CLAUDE.md',
        content: lines.join('\n'),
        sourceMapping: 'morphkit:claude-md',
        confidence: 'high',
        warnings: [],
    };
}

// ---------------------------------------------------------------------------
// README
// ---------------------------------------------------------------------------

function generateReadme(model: SemanticAppModel, stats: GeneratedProject['stats']): GeneratedFile {
    const appName = model.appName ?? 'MyApp';

    return {
        path: '../README.md',
        content: `# ${appName}

Generated by [Morphkit](https://github.com/ashlrai/morphkit) from web source analysis.

## Project Stats

- **Total files**: ${stats.totalFiles}
- **High confidence**: ${stats.highConfidence}
- **Medium confidence**: ${stats.mediumConfidence}
- **Low confidence**: ${stats.lowConfidence}

## Structure

\`\`\`
${appName}/
├── ${appName}App.swift       # App entry point
├── ContentView.swift          # Root navigation
├── Models/                    # Codable data models
├── Views/                     # SwiftUI views
├── Navigation/                # Router and routes
├── Networking/                # API client and DTOs
├── State/                     # Observable stores
└── Assets.xcassets/           # Colors and images
\`\`\`

## Requirements

- Xcode 15+
- iOS 17+
- Swift 5.9+

## Warnings

${stats.warnings.length > 0 ? stats.warnings.map((w) => `- ${w}`).join('\n') : 'None'}

## Getting Started

Open \`Package.swift\` in Xcode to build and run the project.

## Notes

This project was automatically generated and may need manual adjustments:

1. Replace placeholder API base URL in \`Networking/APIConfiguration.swift\`.
2. Add app icon to \`Assets.xcassets/AppIcon.appiconset/\`.
3. Review all files marked with "medium" or "low" confidence.
`,
        sourceMapping: 'morphkit:readme',
        confidence: 'high',
        warnings: [],
    };
}

// ---------------------------------------------------------------------------
// Package.swift generation
// ---------------------------------------------------------------------------

function generatePackageSwift(model: SemanticAppModel): GeneratedFile {
    const appName = pascalCase(model.appName ?? 'MyApp');

    return {
        path: '../Package.swift',
        content: `// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "${appName}",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "${appName}", targets: ["${appName}"]),
    ],
    targets: [
        .target(
            name: "${appName}",
            path: "${appName}",
            exclude: ["Info.plist"],
            resources: [
                .process("Assets.xcassets"),
            ]
        ),
        .testTarget(
            name: "${appName}Tests",
            dependencies: ["${appName}"],
            path: "Tests"
        ),
    ]
)
`,
        sourceMapping: 'morphkit:project',
        confidence: 'high',
        warnings: [],
    };
}

// ---------------------------------------------------------------------------
// Xcode workspace settings
// ---------------------------------------------------------------------------

function generateWorkspaceSettings(): GeneratedFile {
    return {
        path: '../.swiftpm/xcode/package.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings',
        content: `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>IDEWorkspaceSharedSettings_AutocreateContextsIfNeeded</key>
    <false/>
</dict>
</plist>
`,
        sourceMapping: 'morphkit:project',
        confidence: 'high',
        warnings: [],
    };
}

// ---------------------------------------------------------------------------
// Swift syntax validation
// ---------------------------------------------------------------------------

/**
 * Validate generated Swift files by running `swiftc --parse` on each one.
 * Returns an array of warning strings for any syntax errors found.
 * Gracefully skips validation if the Swift toolchain is not installed.
 */
async function validateSwiftSyntax(appDir: string, files: GeneratedFile[]): Promise<string[]> {
    // Allow tests to skip expensive swiftc validation
    if (process.env.MORPHKIT_SKIP_SWIFT_VALIDATION === '1') return [];

    const warnings: string[] = [];

    // Check if swiftc is available on PATH
    try {
        execSync('which swiftc', { stdio: 'pipe' });
    } catch {
        return ['Swift toolchain not found — skipping syntax validation'];
    }

    // Filter to only .swift files
    const swiftFiles = files.filter((f) => f.path.endsWith('.swift'));

    for (const file of swiftFiles) {
        // Resolve the full path on disk, handling both relative (../) and normal paths
        const fullPath = file.path.startsWith('..')
            ? resolve(appDir, file.path)
            : join(appDir, file.path);

        try {
            execFileSync('swiftc', ['-parse', fullPath], {
                stdio: 'pipe',
                timeout: 30_000,
            });
        } catch (err: unknown) {
            // swiftc writes syntax errors to stderr
            const stderr = (err as { stderr?: Buffer })?.stderr?.toString() ?? '';
            if (stderr.trim()) {
                // Parse individual error lines from stderr and format them
                // swiftc output format: /path/to/file.swift:LINE:COL: error: message
                const lines = stderr.trim().split('\n');
                for (const line of lines) {
                    // Match swiftc error/warning output lines
                    const match = line.match(/:(\d+):\d+:\s*(error|warning):\s*(.+)$/);
                    if (match) {
                        const [, lineNum, , message] = match;
                        warnings.push(`[${file.path}:${lineNum}] ${message}`);
                    }
                }
                // If no lines matched the pattern, include the raw stderr as a fallback
                if (!warnings.length || !lines.some((l) => /:(\d+):\d+:\s*(error|warning):/.test(l))) {
                    warnings.push(`[${file.path}] Swift syntax error: ${stderr.trim().split('\n')[0]}`);
                }
            } else {
                warnings.push(`[${file.path}] Swift syntax validation failed (unknown error)`);
            }
        }
    }

    return warnings;
}

// ---------------------------------------------------------------------------
// .claude/commands/ generation (Step 1)
// ---------------------------------------------------------------------------

function generateClaudeCommands(model: SemanticAppModel): GeneratedFile[] {
    const appName = pascalCase(model.appName ?? 'MyApp');
    const screens = (model.screens ?? []).filter(s => !isMarketingScreen(s));
    const referenceScreenNames = getReferenceScreenNames(model);
    const files: GeneratedFile[] = [];

    // /complete-screen command
    files.push({
        path: '../.claude/commands/complete-screen.md',
        content: `# Complete Screen: $ARGUMENTS

Gather all context needed to complete the screen named \`$ARGUMENTS\`, then implement all TODOs.

## Steps

1. Read \`${appName}/Views/\${ARGUMENTS}View.swift\` — find all \`MORPHKIT-TODO:\` blocks
2. Read the reference implementation: ${[...referenceScreenNames].slice(0, 2).map(n => `\`${appName}/Views/${pascalCase(n)}View.swift\``).join(' or ')}
3. Read relevant model files from \`${appName}/Models/\` — check @State declarations for type names
4. Read \`${appName}/Networking/APIClient.swift\` — find the methods referenced in the TODOs
5. For each MORPHKIT-TODO block:
   - Follow the pattern shown in the Reference line
   - Use the APIClient method specified
   - Match the endpoint and request/response types
6. Run \`swift build\` to verify the changes compile
7. Report completion status

## Rules
- Use \`@Observable\` not \`ObservableObject\`
- Use \`.task { }\` not \`.onAppear { Task { } }\`
- Use \`KeychainHelper\` not \`UserDefaults\` for tokens
- \`ForEach\` requires \`id:\` parameter or \`Identifiable\` conformance
- \`@State\` must be \`private\`
- Button async actions need \`Task { }\` wrapper
`,
        sourceMapping: 'morphkit:claude-commands',
        confidence: 'high',
        warnings: [],
    });

    // /verify command
    files.push({
        path: '../.claude/commands/verify.md',
        content: `# Verify Project Completion

Count remaining TODOs, check build status, and report completion percentage.

## Steps

1. Search all \`.swift\` files in \`${appName}/\` for \`MORPHKIT-TODO:\` comments
2. Group TODOs by category (wire-api-fetch, wire-api-action, wire-navigation, wire-mutation)
3. Count TODOs per file from \`MORPHKIT-TODO-COUNT:\` headers
4. Run \`swift build\` and report errors
5. Check if API base URL is still placeholder in \`${appName}/Networking/APIConfiguration.swift\`
6. Check if auth is still stubbed in \`${appName}/State/AuthManager.swift\`

## Output Format

\`\`\`
Build Status:        ✅ PASS | ❌ FAIL (N errors)
Screen Completion:   N/M (XX%)
API Wiring:          N/M (XX%)
Overall:             XX% complete

TODO Breakdown:
  wire-api-fetch:    N
  wire-api-action:   N
  wire-navigation:   N

Files with TODOs:
  Views/CartView.swift:     3 TODOs
  Views/CheckoutView.swift: 2 TODOs

Next step:           Complete <ScreenName> (N TODOs)
\`\`\`
`,
        sourceMapping: 'morphkit:claude-commands',
        confidence: 'high',
        warnings: [],
    });

    // /next command
    const screenList = screens
        .filter(s => !referenceScreenNames.has(s.name))
        .map(s => {
            const apiReqs = (s.dataRequirements ?? []).filter(r => r.fetchStrategy === 'api');
            return `- ${s.name} (${s.layout}, ${apiReqs.length} API deps, ${(s.actions ?? []).length} actions)`;
        }).join('\n');

    files.push({
        path: '../.claude/commands/next.md',
        content: `# What to Complete Next

Analyze which screen to complete next based on dependency order and TODO count.

## Decision Criteria (in priority order)

1. **Leaf screens first** — screens that don't navigate to other incomplete screens
2. **Fewer TODOs** — easier wins build momentum
3. **API method availability** — prefer screens whose APIClient methods are already implemented

## Screens to Consider

${screenList}

## Steps

1. Read each View file's \`MORPHKIT-TODO-COUNT:\` header to get TODO counts
2. Check the completion manifest in \`CLAUDE.md\` for dependency info (\`navigatesTo\` field)
3. Identify leaf screens (screens whose \`navigatesTo\` targets are all complete or reference impls)
4. Among leaves, pick the one with fewest TODOs
5. Output: screen name, file path, TODO count, and what TODOs need to be resolved

## Output Format

\`\`\`
Next: Complete <ScreenName>View (<N> TODOs)
File: ${appName}/Views/<ScreenName>View.swift
Reason: Leaf screen with fewest TODOs

TODOs:
  - wire-api-fetch: fetchItems() -> [Item] (GET /api/items)
  - wire-api-action: addToCart(...) (POST /api/cart)

Run: /complete-screen <ScreenName>
\`\`\`
`,
        sourceMapping: 'morphkit:claude-commands',
        confidence: 'high',
        warnings: [],
    });

    // /complete-all command
    files.push({
        path: '../.claude/commands/complete-all.md',
        content: `# Complete All Screens

Systematically complete all remaining screens in dependency order.

## Strategy

1. Run \`/verify\` to get current completion status
2. Read the reference implementation(s): ${[...referenceScreenNames].slice(0, 2).map(n => `\`${appName}/Views/${pascalCase(n)}View.swift\``).join(', ')}
3. Build a dependency graph from the completion manifest in \`CLAUDE.md\`
4. Complete screens bottom-up (leaf screens first):
   a. For each screen, run \`/complete-screen <name>\`
   b. After each screen, run \`swift build\` to verify
   c. If build fails, fix errors before moving to next screen
5. After all screens: run \`/verify\` to confirm 100% completion

## Completion Order Rules

- Reference implementation screens are already done — skip them
- Auth screens should be completed early (other screens may depend on auth state)
- Detail screens before their parent list screens (list needs NavigationLink targets)
- Settings/profile screens last (least critical path)

## Rules
- Use \`@Observable\` not \`ObservableObject\`
- Use \`.task { }\` not \`.onAppear { Task { } }\`
- Use \`KeychainHelper\` not \`UserDefaults\` for tokens
- \`ForEach\` requires \`id:\` parameter or \`Identifiable\` conformance
- \`@State\` must be \`private\`
- Button async actions need \`Task { }\` wrapper
`,
        sourceMapping: 'morphkit:claude-commands',
        confidence: 'high',
        warnings: [],
    });

    return files;
}

// ---------------------------------------------------------------------------
// .claude/settings.json generation (Step 6)
// ---------------------------------------------------------------------------

function generateClaudeSettings(): GeneratedFile {
    return {
        path: '../.claude/settings.json',
        content: JSON.stringify({
            mcpServers: {
                morphkit: {
                    command: 'npx',
                    args: ['-y', 'morphkit-cli@latest', 'mcp'],
                },
            },
        }, null, 2) + '\n',
        sourceMapping: 'morphkit:claude-settings',
        confidence: 'high',
        warnings: [],
    };
}

// ---------------------------------------------------------------------------
// Orchestrator
// ---------------------------------------------------------------------------

export async function generateXcodeProject(
    model: SemanticAppModel,
    outputPath: string,
): Promise<GeneratedProject> {
    const appName = pascalCase(model.appName ?? 'MyApp');
    const appDir = join(outputPath, appName);
    const allFiles: GeneratedFile[] = [];
    const allWarnings: string[] = [];

    // --- Run all generators ---

    // 1. Models (Codable structs)
    const modelFiles = generateSwiftModels(model);
    allFiles.push(...modelFiles);

    // 1b. SwiftData persistence models
    const swiftDataFiles = generateSwiftDataModels(model);
    allFiles.push(...swiftDataFiles);

    // 1c. DataManager (save/fetch for SwiftData)
    const dataManager = generateDataManager(model);
    if (dataManager) allFiles.push(dataManager);

    // 2. Views
    const viewFiles = generateSwiftUIViews(model);
    allFiles.push(...viewFiles);

    // 3. Navigation
    const navFiles = generateNavigation(model);
    allFiles.push(...navFiles);

    // 4. Networking
    const networkFiles = generateNetworkingLayer(model);
    allFiles.push(...networkFiles);

    // 4b. Error UI Components (ErrorBannerView, RetryButton, EmptyStateView, OfflineBannerView)
    const componentFiles = generateErrorUIComponents();
    allFiles.push(...componentFiles);

    // 5. State
    const stateFiles = generateStateLayer(model);
    allFiles.push(...stateFiles);

    // 6. App entry
    allFiles.push(generateAppEntry(model));

    // 7. Info.plist
    allFiles.push(generateInfoPlist(model));

    // 8. Assets
    const assetFiles = generateAssets(model);
    allFiles.push(...assetFiles);

    // 9. Tests
    const testFiles = generateTestStubs(model);
    allFiles.push(...testFiles);

    // 10. Package.swift (at output root, one level above app folder)
    allFiles.push(generatePackageSwift(model));

    // 11. Xcode workspace settings (opens cleanly in Xcode)
    allFiles.push(generateWorkspaceSettings());

    // 12b. .claude/commands/ (slash commands for AI assistant workflow)
    const commandFiles = generateClaudeCommands(model);
    allFiles.push(...commandFiles);

    // 12c. .claude/settings.json (MCP server auto-registration)
    allFiles.push(generateClaudeSettings());

    // --- Calculate stats ---

    const stats: GeneratedProject['stats'] = {
        totalFiles: allFiles.length,
        highConfidence: allFiles.filter((f) => f.confidence === 'high').length,
        mediumConfidence: allFiles.filter((f) => f.confidence === 'medium').length,
        lowConfidence: allFiles.filter((f) => f.confidence === 'low').length,
        warnings: [],
    };

    // Collect all warnings
    for (const file of allFiles) {
        for (const w of file.warnings) {
            stats.warnings.push(`[${file.path}] ${w}`);
        }
    }

    // 12. README (needs stats)
    allFiles.push(generateReadme(model, stats));

    // 13. CLAUDE.md (AI-assistant context — needs stats for warnings)
    allFiles.push(generateClaudeMd(model, stats));

    // Update total
    stats.totalFiles = allFiles.length;

    // --- Write files to disk ---

    const resolvedAppDir = resolve(appDir);

    for (const file of allFiles) {
        // Security: reject paths containing traversal sequences or absolute paths
        if (file.path.includes('..') && normalize(file.path).startsWith('..')) {
            // Allow controlled parent references (e.g., ../Package.swift, ../README.md)
            // but verify the resolved path stays within the output directory
            const fullPath = resolve(appDir, file.path);
            const resolvedOutputDir = resolve(outputPath) + '/';
            if (!fullPath.startsWith(resolvedOutputDir) && fullPath !== resolve(outputPath)) {
                allWarnings.push(`[${file.path}] Skipped: path resolves outside output directory`);
                continue;
            }
            const dir = dirname(fullPath);
            await mkdir(dir, { recursive: true });
            await writeFile(fullPath, file.content, 'utf-8');
        } else {
            const fullPath = join(appDir, file.path);
            const normalizedFull = resolve(fullPath);
            // Verify resolved path is within the app directory or output directory
            if (!normalizedFull.startsWith(resolvedAppDir + '/') && normalizedFull !== resolvedAppDir && !normalizedFull.startsWith(resolve(outputPath) + '/')) {
                allWarnings.push(`[${file.path}] Skipped: path resolves outside output directory`);
                continue;
            }
            const dir = dirname(fullPath);
            await mkdir(dir, { recursive: true });
            await writeFile(fullPath, file.content, 'utf-8');
        }
    }

    // --- Validate Swift syntax ---

    const syntaxWarnings = await validateSwiftSyntax(appDir, allFiles);
    if (syntaxWarnings.length > 0) {
        stats.warnings.push(...syntaxWarnings);
    }

    return {
        appName,
        files: allFiles,
        outputPath: appDir,
        stats,
    };
}
